// Guías: contenido útil que enlaza a las herramientas. Bloques: ['p'|'h2'|'ul'|'ol'|'cta'|'table', ...].
// En el texto, [[slug]] o [[slug|texto]] enlaza a una herramienta.
export const articles = [
  {
    slug: 'que-es-webp', title: '¿Qué es WebP y cuándo usarlo?', tools: ['convertir-a-webp', 'webp-a-jpg', 'webp-a-png'], date: '2026-09-24',
    description: 'Qué es el formato WebP, cuánto pesa frente a JPG y PNG, qué compatibilidad tiene y cuándo conviene usarlo o convertirlo.',
    blocks: [
      ['p', 'WebP es un formato de imagen creado por Google en 2010 para la web. Admite compresión con pérdida (como JPG) y sin pérdida (como PNG), transparencia y animación, todo en un mismo formato.'],
      ['h2', 'Cuánto pesa frente a JPG y PNG'],
      ['p', 'Con una calidad visual equivalente, una foto en WebP suele pesar entre un 25 % y un 35 % menos que en JPG. Frente a PNG, las imágenes con transparencia pueden reducirse a la mitad o menos. Menos peso significa páginas que cargan antes, sobre todo en móvil.'],
      ['h2', 'Compatibilidad'],
      ['p', 'Todos los navegadores actuales (Chrome, Edge, Firefox y Safari desde la versión 14) muestran WebP. Donde todavía da problemas es fuera del navegador: algunos programas de edición antiguos, ciertas plataformas de impresión o formularios que solo aceptan JPG.'],
      ['h2', 'Cuándo usarlo'],
      ['ul', ['Imágenes de tu web o tienda online: casi siempre es la mejor opción.', 'Capturas o logotipos con transparencia: sustituto ligero de PNG.', 'Archivo o impresión: mejor conserva el original en JPG o PNG.']],
      ['p', 'Si tienes imágenes en JPG o PNG para tu web, conviértelas con [[convertir-a-webp]]. Si recibes un WebP y no puedes abrirlo, pásalo a [[webp-a-jpg|JPG]] o a [[webp-a-png|PNG]].'],
      ['cta', 'convertir-a-webp'],
    ],
  },
  {
    slug: 'como-comprimir-un-pdf', title: 'Cómo comprimir un PDF sin perder calidad', tools: ['comprimir-pdf', 'comprimir-imagen', 'dividir-pdf'], date: '2026-09-24',
    description: 'Por qué pesa tanto un PDF y cómo reducirlo: optimización sin pérdida, compresión de escaneados y trucos para no perder legibilidad.',
    blocks: [
      ['p', 'Casi siempre que un PDF pesa demasiado es por las imágenes: escaneos a alta resolución, fotos de móvil o gráficos exportados sin optimizar. El texto, en cambio, ocupa muy poco.'],
      ['h2', 'Elige el método según el tipo de PDF'],
      ['table', ['Tipo de PDF', 'Método recomendado', 'Resultado'], [['Generado desde Word, Google Docs…', 'Sin pérdida', 'Reducción pequeña; el documento queda idéntico'], ['Escaneado (fotos de páginas)', 'Compresión fuerte', 'Reducción grande (a menudo del 60–90 %)'], ['Con muchas fotos', 'Compresión fuerte', 'Reducción grande; el texto deja de ser seleccionable']]],
      ['h2', 'Paso a paso'],
      ['ol', ['Abre [[comprimir-pdf]] y elige tu archivo: se procesa en tu navegador, no se sube.', 'Empieza por «Sin pérdida». Si apenas baja, prueba «Fuerte».', 'Comprueba el resultado antes de enviarlo: amplía una página y revisa que se lee bien.']],
      ['h2', 'Otros trucos'],
      ['ul', ['Si solo necesitas enviar unas páginas, sepáralas con [[dividir-pdf]]: menos páginas, menos peso.', 'Si vas a crear el PDF desde fotos, comprímelas antes con [[comprimir-imagen]] y únelas con [[jpg-a-pdf]].', 'Al escanear, 150–200 ppp son suficientes para documentos de texto; 300 ppp solo si vas a imprimir.']],
      ['cta', 'comprimir-pdf'],
    ],
  },
  {
    slug: 'como-convertir-jpg-a-png', title: 'Cómo convertir JPG a PNG (y cuándo merece la pena)', tools: ['jpg-a-png', 'png-a-jpg', 'comprimir-imagen'], date: '2026-09-24',
    description: 'Cómo pasar una imagen de JPG a PNG en segundos, qué cambia realmente al convertirla y cuándo conviene hacerlo.',
    blocks: [
      ['p', 'Convertir de JPG a PNG es inmediato, pero conviene saber qué ocurre: PNG guarda los píxeles sin pérdida, así que el archivo pesará bastante más y no recuperará la calidad que el JPG ya perdió.'],
      ['h2', 'Cómo hacerlo'],
      ['ol', ['Abre [[jpg-a-png]].', 'Arrastra una o varias fotos.', 'Pulsa «Convertir» y descarga los PNG (o todos en un ZIP).']],
      ['h2', '¿Cuándo tiene sentido?'],
      ['ul', ['Vas a editar la imagen muchas veces: cada guardado en JPG pierde un poco más de calidad; en PNG no.', 'Necesitas añadir transparencia después (por ejemplo, recortar un logotipo).', 'Una plataforma te exige PNG.']],
      ['p', 'Si lo que buscas es que la imagen pese menos, haz lo contrario: [[png-a-jpg]] o [[comprimir-imagen]].'],
      ['cta', 'jpg-a-png'],
    ],
  },
  {
    slug: 'diferencia-entre-jpg-y-png', title: 'JPG o PNG: diferencias y cuál elegir', tools: ['png-a-jpg', 'jpg-a-png', 'convertir-a-webp'], date: '2026-09-24',
    description: 'Diferencias entre JPG y PNG: compresión, transparencia, peso y usos recomendados, con una tabla para elegir rápido.',
    blocks: [
      ['p', 'JPG y PNG son los dos formatos de imagen más usados, pero están pensados para cosas distintas. Elegir bien puede dividir el peso de una imagen por diez.'],
      ['table', ['', 'JPG', 'PNG'], [['Compresión', 'Con pérdida (ajustable)', 'Sin pérdida'], ['Transparencia', 'No', 'Sí'], ['Peso en fotos', 'Bajo', 'Muy alto'], ['Peso en capturas y logos', 'Medio, con artefactos', 'Bajo y nítido'], ['Ideal para', 'Fotografías', 'Capturas, logos, gráficos con texto']]],
      ['h2', 'La regla rápida'],
      ['ul', ['¿Es una foto? JPG (o WebP para la web).', '¿Tiene texto, bordes nítidos o transparencia? PNG.', '¿Es para una web moderna? Considera [[convertir-a-webp|WebP]], que combina lo mejor de ambos.']],
      ['p', 'Puedes cambiar entre formatos en cualquier momento con [[png-a-jpg]] y [[jpg-a-png]].'],
      ['cta', 'png-a-jpg'],
    ],
  },
  {
    slug: 'como-calcular-el-iva', title: 'Cómo calcular el IVA: sumar y quitar el IVA de un precio', tools: ['calculadora-iva', 'calculadora-porcentajes'], date: '2026-09-24',
    description: 'Fórmulas para añadir y quitar el IVA (21 %, 10 %, 4 %), el error más común al desglosarlo y ejemplos resueltos.',
    blocks: [
      ['p', 'El IVA se calcula siempre sobre la base imponible, es decir, sobre el precio sin impuestos. De ahí salen las dos fórmulas que necesitas.'],
      ['h2', 'Añadir el IVA'],
      ['p', 'Total = base × (1 + tipo ÷ 100). Con IVA del 21 %: 100 € × 1,21 = 121 €.'],
      ['h2', 'Quitar el IVA (desglosar)'],
      ['p', 'Base = total ÷ (1 + tipo ÷ 100). Si un precio de 121 € incluye IVA del 21 %: 121 ÷ 1,21 = 100 €, y el IVA son 21 €.'],
      ['h2', 'El error más común'],
      ['p', 'Restar el 21 % al precio final: 121 € − 21 % = 95,59 €, que no es la base correcta. El porcentaje se aplicó sobre la base, así que hay que dividir, no restar.'],
      ['h2', 'Tipos de IVA en España'],
      ['table', ['Tipo', '%', 'Ejemplos'], [['General', '21 %', 'La mayoría de bienes y servicios'], ['Reducido', '10 %', 'Hostelería, transporte de viajeros, algunos alimentos'], ['Superreducido', '4 %', 'Pan, leche, libros, medicamentos']]],
      ['p', 'Para no hacer cuentas a mano usa la [[calculadora-iva]]; si necesitas otros porcentajes, la [[calculadora-porcentajes]].'],
      ['cta', 'calculadora-iva'],
    ],
  },
  {
    slug: 'que-es-json', title: '¿Qué es JSON? Guía rápida con ejemplos', tools: ['formateador-json', 'validador-json'], date: '2026-09-24',
    description: 'Qué es JSON, cómo es su sintaxis, qué tipos de datos admite y cuáles son los errores más habituales al escribirlo.',
    blocks: [
      ['p', 'JSON (JavaScript Object Notation) es un formato de texto para intercambiar datos. Lo usan casi todas las APIs web, muchos archivos de configuración y bases de datos documentales.'],
      ['h2', 'Sintaxis básica'],
      ['ul', ['Objetos entre llaves con pares "clave": valor separados por comas.', 'Listas (arrays) entre corchetes.', 'Valores: cadenas entre comillas dobles, números, true, false, null, objetos o arrays.']],
      ['h2', 'Errores más comunes'],
      ['ul', ['Comillas simples: JSON solo admite comillas dobles.', 'Coma después del último elemento.', 'Claves sin comillas.', 'Comentarios: el estándar no los permite.']],
      ['p', 'Pega tu JSON en el [[validador-json]] para localizar el error exacto, o en el [[formateador-json]] para hacerlo legible.'],
      ['cta', 'formateador-json'],
    ],
  },
  {
    slug: 'que-es-base64', title: '¿Qué es Base64 y para qué sirve?', tools: ['base64-codificar', 'base64-decodificar', 'imagen-a-base64'], date: '2026-09-24',
    description: 'Qué es la codificación Base64, para qué se usa, por qué no es cifrado y cuánto aumenta el tamaño de los datos.',
    blocks: [
      ['p', 'Base64 es una forma de representar datos binarios (una imagen, un archivo) usando solo 64 caracteres de texto seguros: letras, números, + y /. Así los datos pueden viajar por canales que solo aceptan texto, como el correo electrónico o un JSON.'],
      ['h2', 'Para qué se usa'],
      ['ul', ['Adjuntos de correo electrónico.', 'Imágenes pequeñas incrustadas en HTML o CSS (data URI).', 'Tokens como los JWT.', 'Enviar archivos dentro de una API JSON.']],
      ['h2', 'Lo que no es'],
      ['p', 'Base64 no es cifrado: cualquiera puede decodificarlo al instante. Nunca lo uses para «ocultar» contraseñas o datos sensibles.'],
      ['h2', 'El coste: un 33 % más'],
      ['p', 'Cada 3 bytes se convierten en 4 caracteres, así que el resultado ocupa aproximadamente un tercio más que el original.'],
      ['p', 'Prueba a [[base64-codificar|codificar]] o [[base64-decodificar|decodificar]] texto, o convierte una [[imagen-a-base64|imagen a Base64]].'],
      ['cta', 'base64-codificar'],
    ],
  },
];
