const n = (name, label, extra = {}) => ({ name, type: 'number', label, half: true, step: 'any', ...extra });
const d = (name, label, extra = {}) => ({ name, type: 'date', label, half: true, ...extra });
const common = { family: 'calc', icon: 'calc', live: true };

export default [
  {
    ...common, slug: 'calculadora-porcentajes', name: 'Calculadora de porcentajes', icon: 'percent', popularity: 90,
    short: 'Calcula el X % de una cifra, qué porcentaje representa un número y la variación porcentual entre dos valores.',
    seoTitle: 'Calculadora de porcentajes online',
    description: 'Calcula porcentajes fácilmente: el X % de un número, qué porcentaje es una cifra de otra, aumentos, disminuciones y variación porcentual.',
    keywords: ['calcular porcentaje', 'sacar porcentaje', 'tanto por ciento', 'variacion porcentual', 'aumento porcentual', 'que porcentaje es'],
    fields: [{ name: 'modo', type: 'select', label: '¿Qué quieres calcular?', value: 'de', options: [['de', '¿Cuánto es el X % de Y?'], ['que', '¿Qué % es X de Y?'], ['var', 'Variación % de X a Y'], ['mas', 'Y aumentado un X %'], ['menos', 'Y disminuido un X %']] }, n('x', 'X'), n('y', 'Y')],
    howto: { title: 'Cómo calcular un porcentaje', steps: ['Elige el tipo de cálculo.', 'Introduce los dos valores.', 'El resultado aparece al instante junto con la fórmula.'] },
    about: ['El X % de Y se calcula como Y × X ÷ 100. Para saber qué porcentaje es X de Y: X ÷ Y × 100. La variación porcentual de un valor inicial a uno final es (final − inicial) ÷ inicial × 100.'],
    faq: [['¿Subir un 20 % y luego bajar un 20 % deja el mismo precio?', 'No. 100 + 20 % = 120, y 120 − 20 % = 96. El segundo porcentaje se aplica sobre una base mayor.']],
    related: ['calculadora-iva', 'calculadora-descuentos', 'regla-de-tres'],
  },
  {
    ...common, slug: 'calculadora-iva', name: 'Calculadora de IVA', icon: 'receipt', popularity: 92,
    short: 'Añade o quita el IVA de un precio con los tipos españoles (21 %, 10 %, 4 %) o cualquier otro.',
    seoTitle: 'Calculadora de IVA: añadir y quitar IVA (21 %, 10 %, 4 %)',
    description: 'Calcula el IVA de un precio: suma el IVA a una base imponible o desglosa un precio con IVA incluido. Tipos 21 %, 10 %, 4 % o personalizado.',
    keywords: ['calcular iva', 'quitar iva', 'sumar iva', 'desglosar iva', 'precio sin iva', 'base imponible', 'iva 21'],
    fields: [n('importe', 'Importe (€)', { min: 0, placeholder: '100' }), { name: 'tipo', type: 'select', label: 'Tipo de IVA', value: '21', half: true, options: [['21', 'General 21 %'], ['10', 'Reducido 10 %'], ['4', 'Superreducido 4 %'], ['otro', 'Otro…']] },
      n('otro', 'Otro tipo (%)', { min: 0, max: 100, showIf: 'tipo=otro' }), { name: 'modo', type: 'select', label: 'El importe es', value: 'sin', half: true, options: [['sin', 'Sin IVA (añadir IVA)'], ['con', 'Con IVA (quitar IVA)']] }],
    howto: { title: 'Cómo calcular el IVA', steps: ['Escribe el importe.', 'Elige el tipo de IVA.', 'Indica si el importe ya incluye IVA o no.'] },
    about: ['Para añadir el IVA: total = base × (1 + tipo ÷ 100). Para quitarlo: base = total ÷ (1 + tipo ÷ 100). Un error frecuente es restar el 21 % al total: eso da una base incorrecta.', 'Tipos vigentes en España peninsular y Baleares: 21 % general, 10 % reducido (hostelería, transporte, algunos alimentos) y 4 % superreducido (pan, leche, libros, medicamentos). Canarias usa IGIC y Ceuta y Melilla IPSI, con otros tipos.'],
    faq: [['¿Por qué no puedo quitar el IVA restando un 21 %?', 'Porque el 21 % se calculó sobre la base, no sobre el total. De 121 € quitar el 21 % da 95,59 €, pero la base real es 100 €.'], ['¿Los tipos están actualizados?', 'Son los tipos generales del IVA español. Algunos productos tienen tipos temporales o especiales: usa «Otro» para cualquier porcentaje.']],
    related: ['calculadora-porcentajes', 'calculadora-descuentos', 'interes-simple'],
  },
  {
    ...common, slug: 'regla-de-tres', name: 'Regla de tres', icon: 'calc', popularity: 60,
    short: 'Resuelve reglas de tres simples directas e inversas mostrando la operación.',
    seoTitle: 'Calculadora de regla de tres directa e inversa',
    description: 'Calcula una regla de tres simple directa o inversa: si A es a B, ¿cuánto es X para C? Con la fórmula explicada.',
    keywords: ['regla de 3', 'proporcion', 'regla de tres inversa', 'regla de tres directa', 'calcular proporcion'],
    fields: [n('a', 'A'), n('b', 'es a B'), n('c', 'C'), { name: 'tipo', type: 'select', label: 'Proporción', value: 'directa', half: true, options: [['directa', 'Directa'], ['inversa', 'Inversa']] }],
    howto: { title: 'Cómo hacer una regla de tres', steps: ['Introduce la relación conocida: A es a B.', 'Introduce el tercer valor C.', 'Elige directa (más → más) o inversa (más → menos).'] },
    about: ['Directa: X = B × C ÷ A (si 3 kg cuestan 6 €, 5 kg cuestan 10 €). Inversa: X = A × B ÷ C (si 4 personas tardan 6 horas, 8 personas tardan 3 horas).'],
    faq: [['¿Cuándo es inversa?', 'Cuando al aumentar una magnitud la otra disminuye: más trabajadores, menos tiempo; más velocidad, menos duración.']],
    related: ['calculadora-porcentajes', 'calculadora-iva'],
  },
  {
    ...common, slug: 'calculadora-descuentos', name: 'Calculadora de descuentos', icon: 'tag', popularity: 55,
    short: 'Calcula el precio final tras uno o dos descuentos y cuánto ahorras.',
    seoTitle: 'Calculadora de descuentos: precio final y ahorro',
    description: 'Calcula el precio con descuento, el ahorro y el descuento total equivalente cuando se aplican dos rebajas seguidas.',
    keywords: ['calcular descuento', 'precio con descuento', 'rebajas', 'cuanto me ahorro', 'descuento acumulado'],
    fields: [n('precio', 'Precio original (€)', { min: 0 }), n('d1', 'Descuento (%)', { min: 0, max: 100 }), n('d2', 'Segundo descuento (%)', { min: 0, max: 100, help: 'Opcional: se aplica sobre el precio ya rebajado.' })],
    howto: { title: 'Cómo calcular un descuento', steps: ['Escribe el precio original.', 'Añade el porcentaje de descuento (y un segundo si lo hay).', 'Consulta el precio final y el ahorro.'] },
    faq: [['¿Un 20 % + 10 % es un 30 %?', 'No, es un 28 %: el segundo descuento se aplica sobre el precio ya rebajado.']],
    related: ['calculadora-porcentajes', 'calculadora-iva'],
  },
  {
    ...common, slug: 'interes-simple', name: 'Calculadora de interés simple', icon: 'trend', popularity: 30,
    short: 'Calcula los intereses y el capital final con interés simple.',
    seoTitle: 'Calculadora de interés simple',
    description: 'Calcula el interés simple generado por un capital a un tipo anual durante un plazo en años, meses o días.',
    keywords: ['interes simple', 'calcular intereses', 'capital final'],
    fields: [n('capital', 'Capital (€)', { min: 0 }), n('tasa', 'Tipo de interés anual (%)', { min: 0, max: 1000 }), n('plazo', 'Plazo', { min: 0 }), { name: 'unidad', type: 'select', label: 'Unidad del plazo', value: 'a', half: true, options: [['a', 'Años'], ['m', 'Meses'], ['d', 'Días (base 365)']] }],
    howto: { title: 'Cómo calcular el interés simple', steps: ['Introduce el capital inicial.', 'Indica el tipo anual y el plazo.', 'Obtén los intereses y el capital final.'] },
    about: ['Fórmula: I = C × r × t, con r en tanto por uno y t en años. En interés simple los intereses no se reinvierten, a diferencia del compuesto.'],
    faq: [['¿Incluye impuestos?', 'No. Es el rendimiento bruto; en España los intereses tributan como rendimientos del capital mobiliario.']],
    related: ['interes-compuesto', 'calculadora-porcentajes'],
  },
  {
    ...common, slug: 'interes-compuesto', name: 'Calculadora de interés compuesto', icon: 'trend', popularity: 55,
    short: 'Simula cómo crece un capital con interés compuesto y aportaciones periódicas, año a año.',
    seoTitle: 'Calculadora de interés compuesto con aportaciones',
    description: 'Calcula el crecimiento de una inversión con interés compuesto, frecuencia de capitalización y aportaciones mensuales, con tabla año a año.',
    keywords: ['interes compuesto', 'calcular inversion', 'aportaciones mensuales', 'rentabilidad', 'crecimiento capital'],
    fields: [n('capital', 'Capital inicial (€)', { min: 0 }), n('aporte', 'Aportación mensual (€)', { min: 0, value: 0 }), n('tasa', 'Rentabilidad anual (%)', { min: -100, max: 100 }), n('anios', 'Años', { min: 1, max: 100 }),
      { name: 'freq', type: 'select', label: 'Capitalización', value: '12', half: true, options: [['12', 'Mensual'], ['4', 'Trimestral'], ['1', 'Anual'], ['365', 'Diaria']] }],
    howto: { title: 'Cómo calcular el interés compuesto', steps: ['Indica el capital inicial y, si quieres, una aportación mensual.', 'Escribe la rentabilidad anual esperada y los años.', 'Revisa el capital final y la evolución año a año.'] },
    about: ['Con interés compuesto los intereses generan a su vez intereses: C = C₀ × (1 + r/n)^(n·t). La rentabilidad pasada no garantiza la futura: úsalo para comparar escenarios, no como previsión.'],
    faq: [['¿Las aportaciones se hacen a principio o a final de mes?', 'A final de cada mes, que es la hipótesis más prudente.'], ['¿Tiene en cuenta la inflación?', 'No. Si quieres el valor en euros de hoy, resta la inflación prevista a la rentabilidad.']],
    related: ['interes-simple', 'calculadora-porcentajes'],
  },
  {
    ...common, slug: 'calculadora-edad', name: 'Calculadora de edad', icon: 'cake', popularity: 65,
    short: 'Calcula tu edad exacta en años, meses y días, y cuánto falta para tu próximo cumpleaños.',
    seoTitle: 'Calculadora de edad exacta',
    description: 'Calcula la edad exacta a partir de la fecha de nacimiento: años, meses, días, días totales vividos y próximo cumpleaños.',
    keywords: ['cuantos años tengo', 'calcular edad', 'edad exacta', 'fecha de nacimiento', 'dias vividos'],
    fields: [d('nacimiento', 'Fecha de nacimiento'), d('referencia', 'Calcular a fecha de', { value: 'today' })],
    howto: { title: 'Cómo calcular la edad', steps: ['Introduce la fecha de nacimiento.', 'Deja la fecha de hoy o elige otra.', 'Consulta la edad exacta.'] },
    faq: [['¿Qué pasa si nací un 29 de febrero?', 'En años no bisiestos se considera que cumples el 1 de marzo, que es el criterio del Código Civil español para plazos por meses.']],
    related: ['diferencia-fechas', 'conversor-timestamp'],
  },
  {
    ...common, slug: 'diferencia-fechas', name: 'Diferencia entre fechas', icon: 'calendar', popularity: 60,
    short: 'Calcula los días, semanas, meses y días laborables entre dos fechas.',
    seoTitle: 'Calcular días entre dos fechas',
    description: 'Calcula cuántos días hay entre dos fechas, incluidos días laborables (lunes a viernes), semanas y meses.',
    keywords: ['dias entre fechas', 'cuantos dias faltan', 'contar dias', 'dias laborables', 'calcular plazo'],
    fields: [d('inicio', 'Fecha inicial', { value: 'today' }), d('fin', 'Fecha final'), { name: 'incluir', type: 'checkbox', label: 'Incluir el día final' }],
    howto: { title: 'Cómo contar los días entre dos fechas', steps: ['Elige la fecha inicial y la final.', 'Indica si el último día cuenta.', 'Consulta días naturales, laborables, semanas y meses.'] },
    about: ['Los días laborables cuentan de lunes a viernes; no descuentan festivos porque cambian según la comunidad autónoma y el municipio.'],
    faq: [['¿Se tiene en cuenta el cambio de hora?', 'Sí: el cálculo se hace por fechas de calendario, así que el cambio de horario no altera el recuento.']],
    related: ['calculadora-edad', 'conversor-timestamp', 'conversor-tiempo'],
  },
  {
    ...common, slug: 'calculadora-imc', name: 'Calculadora de IMC', icon: 'heart', popularity: 60,
    short: 'Calcula tu índice de masa corporal y su clasificación según la OMS.',
    seoTitle: 'Calculadora de IMC (índice de masa corporal)',
    description: 'Calcula el índice de masa corporal (IMC) con tu peso y altura, y consulta la clasificación de la OMS y el rango de peso saludable.',
    keywords: ['imc', 'indice de masa corporal', 'peso ideal', 'bmi', 'calcular imc'],
    fields: [n('peso', 'Peso (kg)', { min: 1, max: 500 }), n('altura', 'Altura (cm)', { min: 30, max: 260 })],
    howto: { title: 'Cómo calcular el IMC', steps: ['Introduce tu peso en kilos.', 'Introduce tu altura en centímetros.', 'Consulta tu IMC y su categoría.'] },
    about: ['IMC = peso (kg) ÷ altura² (m). Es un indicador poblacional: no distingue músculo de grasa ni es válido para menores de 18 años o embarazadas. Consulta a un profesional sanitario para una valoración personal.'],
    faq: [['¿Qué IMC es saludable?', 'Según la OMS, entre 18,5 y 24,9 en adultos.']],
    related: ['calculadora-calorias', 'conversor-peso'],
  },
  {
    ...common, slug: 'calculadora-calorias', name: 'Calculadora de calorías', icon: 'flame', popularity: 45,
    short: 'Estima tu metabolismo basal y las calorías diarias que gastas según tu actividad.',
    seoTitle: 'Calculadora de calorías diarias (TMB)',
    description: 'Estima tu tasa metabólica basal (Mifflin-St Jeor) y las calorías diarias de mantenimiento según tu nivel de actividad.',
    keywords: ['calorias diarias', 'metabolismo basal', 'tmb', 'cuantas calorias necesito', 'gasto calorico'],
    fields: [{ name: 'sexo', type: 'select', label: 'Sexo', value: 'h', half: true, options: [['h', 'Hombre'], ['m', 'Mujer']] }, n('edad', 'Edad (años)', { min: 15, max: 100 }), n('peso', 'Peso (kg)', { min: 30, max: 300 }), n('altura', 'Altura (cm)', { min: 120, max: 250 }),
      { name: 'actividad', type: 'select', label: 'Actividad', value: '1.375', options: [['1.2', 'Sedentaria (poco o nada de ejercicio)'], ['1.375', 'Ligera (1–3 días/semana)'], ['1.55', 'Moderada (3–5 días/semana)'], ['1.725', 'Alta (6–7 días/semana)'], ['1.9', 'Muy alta (trabajo físico + entrenamiento)']] }],
    howto: { title: 'Cómo calcular tus calorías diarias', steps: ['Introduce sexo, edad, peso y altura.', 'Elige tu nivel de actividad.', 'Consulta tu gasto estimado.'] },
    about: ['Se usa la ecuación de Mifflin-St Jeor, la más precisa de las habituales en adultos sanos. Es una estimación con un margen de ±10 %; no sustituye el consejo de un profesional.'],
    faq: [['¿Cuántas calorías para perder peso?', 'Un déficit moderado de 300–500 kcal diarias sobre el mantenimiento es la recomendación habitual. Consulta con un profesional si tienes una condición médica.']],
    related: ['calculadora-imc', 'conversor-energia', 'ritmo-carrera'],
  },
  {
    ...common, slug: 'ritmo-carrera', name: 'Calculadora de ritmo de carrera', icon: 'run', popularity: 40,
    short: 'Calcula tu ritmo por kilómetro y velocidad media a partir de distancia y tiempo.',
    seoTitle: 'Calculadora de ritmo de carrera (min/km)',
    description: 'Calcula el ritmo de carrera en min/km y min/milla y la velocidad media a partir de la distancia y el tiempo. Con tiempos estimados para 5K, 10K, media y maratón.',
    keywords: ['ritmo por kilometro', 'calcular ritmo', 'pace', 'min km', 'ritmo maraton', 'running'],
    fields: [{ name: 'dist', type: 'select', label: 'Distancia', value: '10', half: true, options: [['5', '5 km'], ['10', '10 km'], ['21.0975', 'Media maratón'], ['42.195', 'Maratón'], ['otra', 'Otra…']] }, n('km', 'Distancia (km)', { min: 0.1, showIf: 'dist=otra' }),
      { name: 'tiempo', type: 'text', label: 'Tiempo (hh:mm:ss)', placeholder: '00:50:00', half: true, inputmode: 'numeric' }],
    howto: { title: 'Cómo calcular el ritmo', steps: ['Elige la distancia.', 'Escribe el tiempo total (por ejemplo 52:30 o 1:45:00).', 'Consulta ritmo, velocidad y equivalencias.'] },
    about: ['Las equivalencias usan la fórmula de Riegel (T₂ = T₁ × (D₂/D₁)^1,06), una estimación que asume entrenamiento adecuado para la distancia.'],
    faq: [['¿Qué es el ritmo?', 'El tiempo que tardas en recorrer un kilómetro. Un ritmo de 5:00 min/km equivale a 12 km/h.']],
    related: ['conversor-velocidad', 'calculadora-calorias', 'calculadora-1rm'],
  },
  {
    ...common, slug: 'calculadora-1rm', name: 'Calculadora de 1RM', icon: 'dumbbell', popularity: 30,
    short: 'Estima tu repetición máxima (1RM) y los pesos para cada porcentaje de entrenamiento.',
    seoTitle: 'Calculadora de 1RM (repetición máxima)',
    description: 'Estima tu 1RM con las fórmulas de Epley y Brzycki a partir del peso y las repeticiones, con tabla de porcentajes.',
    keywords: ['1rm', 'repeticion maxima', 'rm', 'fuerza maxima', 'porcentajes entrenamiento'],
    fields: [n('peso', 'Peso levantado (kg)', { min: 1 }), n('reps', 'Repeticiones', { min: 1, max: 20, step: 1 })],
    howto: { title: 'Cómo estimar tu 1RM', steps: ['Introduce el peso y las repeticiones completadas.', 'Consulta el 1RM estimado y la tabla de porcentajes.'] },
    about: ['Epley: 1RM = peso × (1 + reps/30). Brzycki: 1RM = peso × 36 / (37 − reps). Son más precisas con menos de 10 repeticiones.'],
    faq: [['¿Es seguro probar mi 1RM real?', 'Solo con técnica consolidada, calentamiento y ayudante. La estimación evita tener que hacerlo.']],
    related: ['ritmo-carrera', 'calculadora-calorias'],
  },
  {
    ...common, slug: 'calculadora-media', name: 'Calculadora de media, mediana y moda', icon: 'chart', popularity: 40, live: true,
    short: 'Calcula media, mediana, moda, desviación típica y más de una lista de números.',
    seoTitle: 'Calculadora de promedio, mediana y moda',
    description: 'Calcula el promedio (media aritmética), la mediana, la moda, el rango y la desviación típica de una lista de números.',
    keywords: ['promedio', 'media aritmetica', 'mediana', 'moda', 'desviacion estandar', 'calcular promedio'],
    fields: [{ name: 'datos', type: 'textarea', label: 'Números', placeholder: '7, 8.5, 6, 9\no uno por línea', rows: 5 }],
    howto: { title: 'Cómo calcular la media', steps: ['Escribe o pega los números separados por comas, espacios o saltos de línea.', 'Consulta todas las medidas al instante.'] },
    faq: [['¿Uso punto o coma decimal?', 'Ambos: «7,5» y «7.5» se interpretan igual. Separa los números con espacios, punto y coma o saltos de línea si usas coma decimal.']],
    related: ['calculadora-notas', 'calculadora-porcentajes'],
  },
  {
    ...common, slug: 'calculadora-notas', name: 'Calculadora de nota media ponderada', icon: 'grad', popularity: 40,
    short: 'Calcula tu nota media ponderada según el peso de cada examen o asignatura.',
    seoTitle: 'Calculadora de nota media ponderada',
    description: 'Calcula la nota media ponderada con el peso o los créditos de cada nota, y qué nota necesitas en el siguiente examen.',
    keywords: ['nota media', 'media ponderada', 'calcular nota', 'creditos', 'que nota necesito'],
    fields: [{ name: 'notas', type: 'textarea', label: 'Nota y peso (uno por línea)', placeholder: '7.5 30\n6 30\n8 40', rows: 6, help: 'Formato: nota espacio peso (porcentaje o créditos). Sin peso cuenta como 1.' }, n('objetivo', '¿Qué media quieres?', { help: 'Opcional', min: 0 }), n('pesoRestante', 'Peso de lo que falta', { help: 'Opcional', min: 0 })],
    howto: { title: 'Cómo calcular la media ponderada', steps: ['Escribe cada nota con su peso en una línea.', 'Opcional: indica la media objetivo y el peso pendiente.', 'Consulta tu media y la nota que necesitas.'] },
    about: ['Media ponderada = Σ(nota × peso) ÷ Σ(peso). Sirve igual con porcentajes (30, 30, 40) que con créditos ECTS (6, 4.5, 9).'],
    faq: [['¿Funciona con notas sobre 10 y sobre 100?', 'Sí, siempre que todas usen la misma escala.']],
    related: ['calculadora-media', 'calculadora-porcentajes'],
  },
];
