const code = (extra = {}) => ({ name: 'texto', type: 'textarea', label: 'Entrada', rows: 10, mono: true, ...extra });
const common = { family: 'dev', icon: 'code' };
const privacyFaq = ['¿Se envían mis datos a algún servidor?', 'No. La herramienta se ejecuta en tu navegador; lo que pegas no sale de tu dispositivo.'];

export default [
  {
    ...common, slug: 'formateador-json', name: 'Formateador JSON', icon: 'braces', live: true, popularity: 80,
    short: 'Formatea, embellece, minifica y ordena JSON con detección de errores exacta.',
    seoTitle: 'Formateador JSON online (JSON beautifier y minify)',
    description: 'Formatea y embellece JSON con sangría de 2 o 4 espacios, minifícalo u ordena sus claves. Indica la línea exacta de cualquier error.',
    keywords: ['json formatter', 'json beautifier', 'formatear json', 'minificar json', 'json pretty print', 'indentar json'],
    fields: [code({ placeholder: '{"nombre":"Ana","edad":31}' }), { name: 'sangria', type: 'select', label: 'Formato', value: '2', half: true, options: [['2', '2 espacios'], ['4', '4 espacios'], ['tab', 'Tabulador'], ['min', 'Minificado']] }, { name: 'ordenar', type: 'checkbox', label: 'Ordenar claves A-Z', half: true }],
    howto: { title: 'Cómo formatear JSON', steps: ['Pega el JSON.', 'Elige la sangría o minificado.', 'Copia o descarga el resultado.'] },
    faq: [privacyFaq, ['¿Acepta comentarios o comas finales?', 'No: el estándar JSON no los permite. La herramienta te indicará la posición exacta para que los quites.']],
    related: ['validador-json', 'base64-codificar', 'decodificador-jwt'],
  },
  {
    ...common, slug: 'validador-json', name: 'Validador JSON', icon: 'check', live: true, popularity: 55,
    short: 'Comprueba si un JSON es válido y localiza la línea y columna del error.',
    seoTitle: 'Validador JSON online',
    description: 'Valida JSON al instante y localiza la línea y columna exactas del error, con una explicación comprensible.',
    keywords: ['json validator', 'validar json', 'json lint', 'error json', 'comprobar json'],
    fields: [code({ placeholder: 'Pega aquí el JSON…' })],
    howto: { title: 'Cómo validar JSON', steps: ['Pega el JSON.', 'Si hay un error verás la línea, la columna y el fragmento afectado.'] },
    about: ['Errores más comunes: comillas simples en vez de dobles, comas después del último elemento, claves sin comillas y comentarios. JSON no admite ninguno de ellos.'],
    faq: [privacyFaq],
    related: ['formateador-json', 'probador-regex'],
  },
  {
    ...common, slug: 'base64-codificar', name: 'Codificar Base64', icon: 'binary', live: true, popularity: 55,
    short: 'Codifica texto a Base64 (compatible con UTF-8, tildes y emojis).',
    seoTitle: 'Codificar texto a Base64 online',
    description: 'Convierte texto a Base64 con soporte completo de UTF-8 (tildes, ñ, emojis) y variante segura para URL.',
    keywords: ['base64 encode', 'codificar base64', 'texto a base64', 'convertir base64'],
    fields: [code({ label: 'Texto', mono: false }), { name: 'url', type: 'checkbox', label: 'Variante URL-safe (- y _ sin =)' }],
    howto: { title: 'Cómo codificar en Base64', steps: ['Escribe o pega el texto.', 'Copia el resultado en Base64.'] },
    about: ['Base64 no es cifrado: cualquiera puede decodificarlo. Sirve para transportar datos binarios o texto por canales que solo aceptan ASCII. Para imágenes usa Imagen a Base64.'],
    faq: [privacyFaq],
    related: ['base64-decodificar', 'imagen-a-base64', 'url-codificar'],
  },
  {
    ...common, slug: 'base64-decodificar', name: 'Decodificar Base64', icon: 'binary', live: true, popularity: 50,
    short: 'Decodifica Base64 a texto legible, incluida la variante URL-safe.',
    seoTitle: 'Decodificar Base64 a texto online',
    description: 'Decodifica cadenas Base64 (estándar o URL-safe) a texto UTF-8 y detecta si el contenido es binario.',
    keywords: ['base64 decode', 'decodificar base64', 'base64 a texto'],
    fields: [code({ label: 'Base64', placeholder: 'SG9sYSBtdW5kbw==' })],
    howto: { title: 'Cómo decodificar Base64', steps: ['Pega la cadena Base64.', 'Lee o copia el texto decodificado.'] },
    faq: [privacyFaq, ['¿Qué pasa si el contenido es una imagen?', 'Si el Base64 es un data URI de imagen, se mostrará una vista previa y podrás descargarla.']],
    related: ['base64-codificar', 'decodificador-jwt', 'url-decodificar'],
  },
  {
    ...common, slug: 'url-codificar', name: 'Codificar URL', icon: 'link', live: true, popularity: 35,
    short: 'Codifica texto para usarlo en una URL (percent-encoding).',
    seoTitle: 'URL encode online',
    description: 'Codifica texto con percent-encoding para URLs y parámetros de consulta: espacios, tildes y símbolos se convierten a %XX.',
    keywords: ['url encode', 'codificar url', 'percent encoding', 'escapar url', 'encodeuricomponent'],
    fields: [code({ label: 'Texto' }), { name: 'modo', type: 'select', label: 'Modo', value: 'comp', options: [['comp', 'Parámetro (encodeURIComponent)'], ['full', 'URL completa (encodeURI)']] }],
    howto: { title: 'Cómo codificar una URL', steps: ['Pega el texto o la URL.', 'Elige si es un parámetro o una URL completa.', 'Copia el resultado.'] },
    faq: [['¿Qué modo uso?', '«Parámetro» para valores que van tras ?clave=, porque codifica también / ? & =. «URL completa» conserva esos caracteres.']],
    related: ['url-decodificar', 'base64-codificar', 'generador-slug'],
  },
  {
    ...common, slug: 'url-decodificar', name: 'Decodificar URL', icon: 'link', live: true, popularity: 35,
    short: 'Convierte %XX de una URL a texto legible y desglosa sus parámetros.',
    seoTitle: 'URL decode online',
    description: 'Decodifica URLs con percent-encoding y desglosa protocolo, dominio, ruta y parámetros de consulta.',
    keywords: ['url decode', 'decodificar url', 'parametros url', 'analizar url'],
    fields: [code({ label: 'URL o texto codificado', rows: 5 })],
    howto: { title: 'Cómo decodificar una URL', steps: ['Pega la URL.', 'Lee el texto decodificado y la tabla de parámetros.'] },
    faq: [['¿Los + se convierten en espacios?', 'Sí, en la parte de consulta (tras ?), que es como los envían los formularios.']],
    related: ['url-codificar', 'base64-decodificar'],
  },
  {
    ...common, slug: 'generador-uuid', name: 'Generador de UUID', icon: 'fingerprint', live: true, popularity: 45,
    short: 'Genera UUID v4 aleatorios o v7 ordenables por tiempo, en lote.',
    seoTitle: 'Generador de UUID v4 y v7 online',
    description: 'Genera UUID/GUID v4 (aleatorios) y v7 (ordenables por fecha) con generador criptográfico, de 1 a 1000 a la vez.',
    keywords: ['uuid', 'guid', 'uuid v4', 'uuid v7', 'generar id unico'],
    fields: [{ name: 'cantidad', type: 'number', label: 'Cantidad', value: 5, min: 1, max: 1000, half: true }, { name: 'version', type: 'select', label: 'Versión', value: '4', half: true, options: [['4', 'v4 (aleatorio)'], ['7', 'v7 (ordenado por tiempo)']] }, { name: 'mayus', type: 'checkbox', label: 'Mayúsculas', half: true }, { name: 'guiones', type: 'checkbox', label: 'Con guiones', value: true, half: true }],
    regenerate: true,
    howto: { title: 'Cómo generar UUID', steps: ['Elige cuántos y qué versión.', 'Copia la lista; pulsa «Generar otros» para nuevos valores.'] },
    about: ['v4 usa 122 bits aleatorios. v7 empieza por la marca de tiempo en milisegundos, así que los identificadores se ordenan por fecha de creación: mejor rendimiento como clave primaria en bases de datos.'],
    faq: [['¿Pueden repetirse?', 'En la práctica no: la probabilidad de colisión con v4 es despreciable incluso generando miles de millones.']],
    related: ['generador-contrasenas', 'generador-hash'],
  },
  {
    ...common, slug: 'generador-hash', name: 'Generador de hash', icon: 'hash', live: true, popularity: 40,
    short: 'Calcula MD5, SHA-1, SHA-256, SHA-384 y SHA-512 de un texto.',
    seoTitle: 'Generador de hash MD5, SHA-1, SHA-256 online',
    description: 'Calcula los hashes MD5, SHA-1, SHA-256, SHA-384 y SHA-512 de cualquier texto en UTF-8, en tu navegador.',
    keywords: ['md5', 'sha256', 'sha1', 'sha512', 'hash', 'checksum', 'calcular hash'],
    fields: [code({ label: 'Texto', mono: false })],
    howto: { title: 'Cómo generar un hash', steps: ['Escribe o pega el texto.', 'Copia el hash del algoritmo que necesites.'] },
    about: ['MD5 y SHA-1 ya no son seguros frente a colisiones: úsalos solo como checksum. Para contraseñas no uses ningún hash simple; usa Argon2, scrypt o bcrypt.'],
    faq: [privacyFaq],
    related: ['generador-uuid', 'base64-codificar', 'generador-contrasenas'],
  },
  {
    ...common, slug: 'generador-contrasenas', name: 'Generador de contraseñas', icon: 'key', live: true, popularity: 60,
    short: 'Crea contraseñas seguras y aleatorias con la longitud y caracteres que elijas.',
    seoTitle: 'Generador de contraseñas seguras',
    description: 'Genera contraseñas seguras con el generador criptográfico del navegador: elige longitud, mayúsculas, números y símbolos. Nunca se envían.',
    keywords: ['contraseña segura', 'generar contraseña', 'password generator', 'clave aleatoria'],
    fields: [{ name: 'longitud', type: 'range', label: 'Longitud', value: 20, min: 8, max: 64 }, { name: 'mayus', type: 'checkbox', label: 'Mayúsculas (A-Z)', value: true, half: true }, { name: 'minus', type: 'checkbox', label: 'Minúsculas (a-z)', value: true, half: true }, { name: 'numeros', type: 'checkbox', label: 'Números (0-9)', value: true, half: true }, { name: 'simbolos', type: 'checkbox', label: 'Símbolos (!@#…)', value: true, half: true }, { name: 'ambiguos', type: 'checkbox', label: 'Evitar parecidos (0/O, l/1)', half: true }, { name: 'cantidad', type: 'number', label: 'Cantidad', value: 5, min: 1, max: 50, half: true }],
    regenerate: true,
    howto: { title: 'Cómo crear una contraseña segura', steps: ['Elige la longitud (recomendado 16 o más).', 'Selecciona los tipos de caracteres.', 'Copia la contraseña y guárdala en un gestor de contraseñas.'] },
    about: ['La seguridad depende sobre todo de la longitud. Una contraseña aleatoria de 16 caracteres con los cuatro tipos tiene más de 100 bits de entropía, fuera del alcance de cualquier ataque por fuerza bruta.'],
    faq: [['¿Se guardan las contraseñas generadas?', 'No. Se generan en tu navegador con crypto.getRandomValues y desaparecen al cerrar la página.']],
    related: ['generador-hash', 'generador-uuid'],
  },
  {
    ...common, slug: 'probador-regex', name: 'Probador de expresiones regulares', icon: 'regex', live: true, popularity: 45,
    short: 'Prueba expresiones regulares JavaScript con resaltado de coincidencias y grupos.',
    seoTitle: 'Regex tester online (JavaScript)',
    description: 'Prueba expresiones regulares en tiempo real: resalta coincidencias, muestra grupos capturados y admite flags g, i, m, s, u.',
    keywords: ['regex', 'regex tester', 'expresion regular', 'probar regex', 'regexp'],
    fields: [{ name: 'patron', type: 'text', label: 'Expresión regular', placeholder: '\\b\\w+@\\w+\\.\\w+\\b', mono: true, half: true }, { name: 'flags', type: 'text', label: 'Flags', value: 'g', placeholder: 'gimsu', mono: true, half: true }, code({ label: 'Texto de prueba', rows: 8, mono: false })],
    howto: { title: 'Cómo probar una regex', steps: ['Escribe el patrón sin barras.', 'Añade los flags (g para todas las coincidencias).', 'Pega el texto y revisa las coincidencias y grupos.'] },
    faq: [['¿Qué motor de regex usa?', 'El de JavaScript de tu navegador (ECMAScript), incluidos grupos con nombre (?<nombre>…) y lookbehind.']],
    related: ['buscar-reemplazar', 'validador-json'],
  },
  {
    ...common, slug: 'conversor-timestamp', name: 'Conversor de timestamp Unix', icon: 'clock', live: true, popularity: 40,
    short: 'Convierte timestamps Unix (segundos o milisegundos) a fecha y viceversa.',
    seoTitle: 'Conversor de timestamp Unix a fecha',
    description: 'Convierte un timestamp Unix en segundos o milisegundos a fecha legible (local, UTC, ISO 8601) y una fecha a timestamp.',
    keywords: ['unix timestamp', 'epoch', 'timestamp a fecha', 'fecha a timestamp', 'epoch converter'],
    fields: [{ name: 'valor', type: 'text', label: 'Timestamp o fecha', placeholder: '1767225600 o 2026-01-01 12:00', mono: true, value: 'now' }],
    howto: { title: 'Cómo convertir un timestamp', steps: ['Pega un timestamp (10 dígitos = segundos, 13 = milisegundos) o una fecha.', 'Consulta todas las representaciones.'] },
    faq: [['¿Qué es el tiempo Unix?', 'Los segundos transcurridos desde el 1 de enero de 1970 a las 00:00 UTC, sin contar segundos intercalares.']],
    related: ['diferencia-fechas', 'generador-uuid'],
  },
  {
    ...common, slug: 'conversor-colores', name: 'Conversor de colores', icon: 'palette', live: true, popularity: 50,
    short: 'Convierte colores entre HEX, RGB, HSL y CMYK, con contraste WCAG.',
    seoTitle: 'Conversor de colores HEX, RGB, HSL',
    description: 'Convierte colores entre HEX, RGB, HSL y CMYK (HEX a RGB, RGB a HEX…) y comprueba su contraste con blanco y negro según WCAG.',
    keywords: ['hex a rgb', 'rgb a hex', 'hsl', 'cmyk', 'color picker', 'codigo de color', 'contraste wcag'],
    fields: [{ name: 'color', type: 'text', label: 'Color', value: '#4f46e5', placeholder: '#4f46e5, rgb(79 70 229), hsl(243 75% 59%)', mono: true, half: true }, { name: 'picker', type: 'color', label: 'Selector', value: '#4f46e5', half: true, syncWith: 'color' }],
    howto: { title: 'Cómo convertir un color', steps: ['Escribe el color en cualquier formato o usa el selector.', 'Copia el formato que necesites.'] },
    about: ['El contraste se calcula con la fórmula de luminancia relativa de WCAG 2: 4,5:1 es el mínimo para texto normal (AA) y 3:1 para texto grande.'],
    faq: [['¿El CMYK es exacto para imprenta?', 'Es una conversión matemática sin perfil de color. Para impresión profesional usa el perfil ICC de tu imprenta.']],
    related: ['extraer-colores', 'minificador-css'],
  },
  {
    ...common, slug: 'minificador-css', name: 'Minificador CSS', icon: 'minimize', live: true, popularity: 30,
    short: 'Minifica CSS eliminando comentarios, espacios y puntos y coma sobrantes.',
    seoTitle: 'Minificar CSS online',
    description: 'Minifica código CSS: elimina comentarios, espacios y saltos de línea innecesarios respetando cadenas y url().',
    keywords: ['css minifier', 'minificar css', 'comprimir css', 'optimizar css'],
    fields: [code({ label: 'CSS', placeholder: '.btn {\n  color: red;\n}' })],
    howto: { title: 'Cómo minificar CSS', steps: ['Pega el CSS.', 'Copia o descarga la versión minificada; verás el ahorro.'] },
    faq: [['¿Puede romper mi CSS?', 'Solo elimina espacios y comentarios; no reordena ni fusiona reglas. Los comentarios /*! … */ de licencia se conservan.']],
    related: ['formateador-css', 'conversor-colores'],
  },
  {
    ...common, slug: 'formateador-css', name: 'Formateador CSS', icon: 'braces', live: true, popularity: 25,
    short: 'Ordena y embellece CSS minificado con sangría legible.',
    seoTitle: 'Formatear CSS online (CSS beautifier)',
    description: 'Formatea CSS minificado o desordenado: una declaración por línea, sangría consistente y reglas separadas.',
    keywords: ['css beautifier', 'formatear css', 'css formatter', 'indentar css'],
    fields: [code({ label: 'CSS' })],
    howto: { title: 'Cómo formatear CSS', steps: ['Pega el CSS.', 'Copia el resultado legible.'] },
    faq: [['¿Soporta @media y anidación?', 'Sí, la sangría sigue la profundidad de las llaves, así que @media, @supports y CSS anidado se formatean correctamente.']],
    related: ['minificador-css', 'formateador-json'],
  },
  {
    ...common, slug: 'decodificador-jwt', name: 'Decodificador JWT', icon: 'key', live: true, popularity: 35,
    short: 'Decodifica la cabecera y el payload de un JSON Web Token y muestra sus fechas.',
    seoTitle: 'Decodificador JWT online',
    description: 'Decodifica tokens JWT: cabecera, payload y fechas de emisión y caducidad (iat, exp, nbf) en formato legible. Sin enviar el token.',
    keywords: ['jwt decoder', 'decodificar jwt', 'json web token', 'jwt debugger'],
    fields: [code({ label: 'Token JWT', rows: 5, placeholder: 'eyJhbGciOi…' })],
    howto: { title: 'Cómo decodificar un JWT', steps: ['Pega el token.', 'Revisa la cabecera, el payload y las fechas.'] },
    about: ['Decodificar no es verificar: la firma solo se comprueba con la clave secreta o pública del emisor. Nunca confíes en un JWT sin verificar su firma en el servidor.'],
    faq: [privacyFaq],
    related: ['base64-decodificar', 'formateador-json'],
  },
];
