const img = (extra = {}) => ({ name: 'archivos', type: 'file', label: 'Imágenes', accept: 'image/jpeg,image/png,image/webp,image/gif,image/bmp', multiple: true, maxMB: 40, maxFiles: 30, ...extra });
const common = { family: 'image', icon: 'image', submit: 'Procesar' };
const faqPriv = ['¿Se suben mis imágenes?', 'No. Se procesan en tu navegador con Canvas: nunca salen de tu dispositivo, así que puedes usar fotos privadas con tranquilidad.'];
const faqMeta = ['¿Se conservan los datos EXIF?', 'No. Al volver a codificar la imagen se eliminan los metadatos (ubicación GPS, cámara, fecha).'];
const steps = (verb) => ['Arrastra tus imágenes o pulsa para elegirlas.', `Ajusta las opciones y pulsa «${verb}».`, 'Descarga cada imagen o todas juntas en un ZIP.'];
const convert = (slug, from, to, pop, extra = {}) => ({
  ...common, slug, name: `${from.toUpperCase()} a ${to.toUpperCase()}`, popularity: pop, submit: 'Convertir', options: { to },
  short: `Convierte imágenes ${from.toUpperCase()} a ${to.toUpperCase()} en tu navegador, por lotes y sin subirlas.`,
  seoTitle: `Convertir ${from.toUpperCase()} a ${to.toUpperCase()} online gratis`,
  description: `Convierte ${from.toUpperCase()} a ${to.toUpperCase()} gratis y sin subir archivos: varias imágenes a la vez, sin marcas de agua.`,
  keywords: [`${from} a ${to}`, `pasar ${from} a ${to}`, `convertir ${from} en ${to}`, `${from} to ${to}`, `cambiar formato ${from}`],
  fields: [img({ label: `Imágenes ${from.toUpperCase()}`, accept: extra.accept || `image/${from === 'jpg' ? 'jpeg' : from}` }), ...(extra.fields || [])],
  howto: { title: `Cómo convertir ${from.toUpperCase()} a ${to.toUpperCase()}`, steps: steps('Convertir') },
  about: extra.about, faq: [faqPriv, ...(extra.faq || [])],
  related: extra.related || ['comprimir-imagen', 'redimensionar-imagen', 'convertir-a-webp'],
});
const bg = { name: 'fondo', type: 'color', label: 'Color de fondo para transparencias', value: '#ffffff', half: true };
const quality = (v = 90) => ({ name: 'calidad', type: 'range', label: 'Calidad', value: v, min: 10, max: 100, half: true, suffix: '%' });

export default [
  {
    ...common, slug: 'comprimir-imagen', name: 'Comprimir imagen', icon: 'compress', popularity: 90, submit: 'Comprimir',
    short: 'Reduce el peso de tus fotos JPG, PNG y WebP manteniendo una buena calidad visual.',
    seoTitle: 'Comprimir imágenes online sin perder calidad',
    description: 'Comprime imágenes JPG, PNG y WebP en tu navegador: reduce su peso hasta un 80 % sin subirlas a ningún servidor. Por lotes y gratis.',
    keywords: ['reducir peso imagen', 'comprimir foto', 'optimizar imagen', 'comprimir jpg', 'comprimir png', 'reducir tamaño foto', 'optimizar imagenes web'],
    fields: [img(), quality(75), { name: 'formato', type: 'select', label: 'Formato de salida', value: 'auto', half: true, options: [['auto', 'Mismo formato (PNG → WebP)'], ['jpeg', 'JPG'], ['webp', 'WebP']] }, { name: 'maxlado', type: 'number', label: 'Lado máximo (px)', placeholder: 'Sin límite', min: 16, max: 16000, half: true, help: 'Opcional: reduce también las dimensiones.' }],
    howto: { title: 'Cómo comprimir una imagen', steps: steps('Comprimir') },
    about: ['Una calidad del 70–80 % suele ser invisible a simple vista y reduce el peso a la mitad o menos. Para la web, limitar el lado mayor a 1920 px ahorra todavía más. Si una imagen ya estaba bien optimizada y el resultado pesa más, se conserva la original.'],
    faq: [faqPriv, faqMeta, ['¿Por qué un PNG se convierte a otro formato?', 'PNG no admite compresión con pérdida, así que por defecto se convierte a WebP, que mantiene la transparencia y pesa mucho menos. Si necesitas JPG, elígelo en «Formato de salida».']],
    related: ['redimensionar-imagen', 'convertir-a-webp', 'png-a-jpg', 'comprimir-pdf'],
  },
  {
    ...common, slug: 'redimensionar-imagen', name: 'Redimensionar imagen', icon: 'resize', popularity: 80, submit: 'Redimensionar',
    short: 'Cambia el tamaño de tus imágenes en píxeles o porcentaje, manteniendo la proporción.',
    seoTitle: 'Redimensionar imagen online (cambiar tamaño en px)',
    description: 'Cambia el tamaño de imágenes JPG, PNG y WebP por píxeles o porcentaje, manteniendo la proporción. Por lotes, en tu navegador.',
    keywords: ['cambiar tamaño imagen', 'redimensionar foto', 'resize image', 'reducir dimensiones', 'escalar imagen', 'cambiar resolucion'],
    fields: [img(), { name: 'modo', type: 'select', label: 'Modo', value: 'px', half: true, options: [['px', 'Por píxeles'], ['pct', 'Por porcentaje']] }, { name: 'pct', type: 'number', label: 'Porcentaje (%)', value: 50, min: 1, max: 1000, half: true, showIf: 'modo=pct' },
      { name: 'ancho', type: 'number', label: 'Ancho (px)', min: 1, max: 16000, half: true, showIf: 'modo=px' }, { name: 'alto', type: 'number', label: 'Alto (px)', min: 1, max: 16000, half: true, showIf: 'modo=px' }, { name: 'proporcion', type: 'checkbox', label: 'Mantener proporción (basta con ancho o alto)', value: true, showIf: 'modo=px' }],
    howto: { title: 'Cómo redimensionar una imagen', steps: steps('Redimensionar') },
    about: ['Con «Mantener proporción» la imagen cabe dentro del ancho y alto indicados sin deformarse. Ampliar una imagen no añade detalle: para impresión parte siempre del original de mayor tamaño.'],
    faq: [faqPriv, faqMeta],
    related: ['comprimir-imagen', 'recortar-imagen', 'rotar-imagen', 'generador-favicon'],
  },
  {
    ...common, slug: 'recortar-imagen', name: 'Recortar imagen', icon: 'crop', popularity: 55, submit: 'Recortar',
    short: 'Recorta una imagen a una proporción (1:1, 16:9, 4:3…) o a medidas exactas.',
    seoTitle: 'Recortar imagen online (1:1, 16:9, 4:3)',
    description: 'Recorta imágenes a proporciones típicas para redes sociales (1:1, 4:5, 16:9, 9:16) o a un área exacta en píxeles, sin subirlas.',
    keywords: ['recortar foto', 'crop image', 'imagen cuadrada', 'recortar 16:9', 'recortar para instagram'],
    fields: [img(), { name: 'proporcion', type: 'select', label: 'Proporción', value: '1:1', half: true, options: [['1:1', '1:1 cuadrado'], ['4:5', '4:5 retrato (Instagram)'], ['16:9', '16:9 panorámico'], ['9:16', '9:16 vertical (stories)'], ['4:3', '4:3'], ['3:2', '3:2'], ['libre', 'Medidas exactas…']] },
      { name: 'ancla', type: 'select', label: 'Zona que se conserva', value: 'center', half: true, showIf: 'proporcion!=libre', options: [['center', 'Centro'], ['top', 'Arriba / izquierda'], ['bottom', 'Abajo / derecha']] },
      { name: 'x', type: 'number', label: 'X (px desde la izquierda)', min: 0, half: true, showIf: 'proporcion=libre', value: 0 }, { name: 'y', type: 'number', label: 'Y (px desde arriba)', min: 0, half: true, showIf: 'proporcion=libre', value: 0 },
      { name: 'ancho', type: 'number', label: 'Ancho (px)', min: 1, half: true, showIf: 'proporcion=libre' }, { name: 'alto', type: 'number', label: 'Alto (px)', min: 1, half: true, showIf: 'proporcion=libre' }],
    howto: { title: 'Cómo recortar una imagen', steps: ['Elige una o varias imágenes.', 'Selecciona la proporción y la zona a conservar (o medidas exactas).', 'Descarga el recorte.'] },
    faq: [faqPriv, ['¿Puedo recortar varias a la vez?', 'Sí: todas se recortan con la misma proporción y ancla, útil para preparar una galería homogénea.']],
    related: ['redimensionar-imagen', 'rotar-imagen', 'comprimir-imagen'],
  },
  {
    ...common, slug: 'rotar-imagen', name: 'Rotar imagen', icon: 'rotate', popularity: 40, submit: 'Rotar',
    short: 'Gira imágenes 90°, 180° o 270° y voltéalas en horizontal o vertical.',
    seoTitle: 'Rotar imagen online (girar y voltear)',
    description: 'Gira imágenes 90, 180 o 270 grados o voltéalas como en un espejo. Por lotes y sin subir archivos.',
    keywords: ['girar imagen', 'girar foto', 'voltear imagen', 'espejo', 'rotate image'],
    fields: [img(), { name: 'giro', type: 'select', label: 'Giro', value: '90', half: true, options: [['0', 'Sin giro'], ['90', '90° derecha'], ['180', '180°'], ['270', '90° izquierda']] }, { name: 'voltear', type: 'select', label: 'Voltear', value: 'no', half: true, options: [['no', 'No'], ['h', 'Horizontal (espejo)'], ['v', 'Vertical']] }],
    howto: { title: 'Cómo rotar una imagen', steps: steps('Rotar') },
    faq: [faqPriv, ['Mi foto aparece girada en algunos programas, ¿por qué?', 'Muchas cámaras guardan la orientación en EXIF en lugar de girar los píxeles. Esta herramienta aplica el giro real a los píxeles, así se ve igual en todas partes.']],
    related: ['recortar-imagen', 'redimensionar-imagen'],
  },
  convert('jpg-a-png', 'jpg', 'png', 70, { about: ['PNG es un formato sin pérdida: la conversión conserva exactamente los píxeles del JPG, pero el archivo pesará más. Conviértelo si necesitas editar la imagen muchas veces o añadir transparencia después.'], faq: [['¿El PNG tendrá mejor calidad?', 'No recupera la calidad perdida en el JPG; solo evita perder más en ediciones futuras.']], related: ['png-a-jpg', 'comprimir-imagen', 'jpg-a-pdf'] }),
  convert('png-a-jpg', 'png', 'jpg', 75, { fields: [quality(90), bg], about: ['JPG no admite transparencia: las zonas transparentes del PNG se rellenan con el color de fondo que elijas (blanco por defecto). Ideal para reducir el peso de capturas y fotos guardadas como PNG.'], related: ['jpg-a-png', 'comprimir-imagen', 'png-a-pdf'] }),
  convert('webp-a-jpg', 'webp', 'jpg', 70, { fields: [quality(90), bg], about: ['WebP es el formato moderno de la web, pero algunos programas antiguos y redes no lo aceptan. JPG es compatible con todo.'], related: ['webp-a-png', 'convertir-a-webp', 'comprimir-imagen'] }),
  convert('webp-a-png', 'webp', 'png', 50, { about: ['PNG conserva la transparencia del WebP y es compatible con cualquier editor de imágenes.'], related: ['webp-a-jpg', 'convertir-a-webp'] }),
  {
    ...convert('convertir-a-webp', 'jpg/png', 'webp', 55, { accept: 'image/jpeg,image/png,image/gif,image/bmp', fields: [quality(80)] }),
    name: 'Convertir a WebP', seoTitle: 'Convertir JPG y PNG a WebP online',
    short: 'Convierte JPG y PNG a WebP para que tu web cargue más rápido.',
    description: 'Convierte imágenes JPG y PNG a WebP: hasta un 30 % más ligeras que JPG con la misma calidad, con soporte de transparencia.',
    keywords: ['jpg a webp', 'png a webp', 'convertir webp', 'optimizar web', 'imagenes webp'],
    howto: { title: 'Cómo convertir imágenes a WebP', steps: steps('Convertir') },
    about: ['WebP lo admiten todos los navegadores actuales. Para una web, suele ser la mejor opción por peso y compatibilidad; guarda el original por si lo necesitas en otro formato.'],
    related: ['webp-a-jpg', 'comprimir-imagen', 'redimensionar-imagen'],
  },
  {
    ...common, slug: 'imagen-a-base64', name: 'Imagen a Base64', icon: 'binary', also: ['desarrollo'], popularity: 35, submit: 'Convertir',
    short: 'Convierte una imagen en un data URI Base64 listo para HTML o CSS.',
    seoTitle: 'Convertir imagen a Base64 online',
    description: 'Convierte imágenes a Base64 (data URI) para incrustarlas en HTML, CSS o JSON. Con fragmentos listos para copiar.',
    keywords: ['image to base64', 'data uri', 'png a base64', 'jpg a base64', 'incrustar imagen'],
    fields: [img({ multiple: false, maxMB: 5, accept: 'image/jpeg,image/png,image/webp,image/gif,image/svg+xml' })],
    howto: { title: 'Cómo convertir una imagen a Base64', steps: ['Elige la imagen.', 'Pulsa Convertir.', 'Copia el data URI o el fragmento HTML/CSS.'] },
    about: ['Base64 aumenta el tamaño un 33 %. Úsalo solo para iconos pequeños (menos de 5–10 KB); para imágenes grandes es mejor un archivo aparte que el navegador pueda cachear.'],
    faq: [faqPriv],
    related: ['base64-codificar', 'base64-decodificar', 'comprimir-imagen'],
  },
  {
    ...common, slug: 'extraer-colores', name: 'Extraer colores de una imagen', icon: 'palette', popularity: 35, submit: 'Extraer',
    short: 'Obtén la paleta de colores dominantes de una imagen con sus códigos HEX.',
    seoTitle: 'Extraer paleta de colores de una imagen',
    description: 'Extrae los colores dominantes de una foto o logo y copia sus códigos HEX y RGB. Ideal para crear paletas de diseño.',
    keywords: ['paleta de colores', 'color picker imagen', 'colores dominantes', 'sacar color de foto', 'codigo hex imagen'],
    fields: [img({ multiple: false }), { name: 'cantidad', type: 'range', label: 'Número de colores', value: 6, min: 2, max: 12 }],
    howto: { title: 'Cómo extraer los colores de una imagen', steps: ['Elige la imagen.', 'Indica cuántos colores quieres.', 'Copia los códigos HEX.'] },
    about: ['Se usa un algoritmo de agrupación (k-means) sobre una versión reducida de la imagen, así que funciona rápido incluso con fotos grandes. Los colores se ordenan por presencia.'],
    faq: [faqPriv],
    related: ['conversor-colores', 'generador-favicon'],
  },
  {
    ...common, slug: 'generador-favicon', name: 'Generador de favicon', icon: 'star', also: ['desarrollo', 'seo'], popularity: 40, submit: 'Generar',
    short: 'Crea favicon.ico y los iconos PNG para web, Apple y Android a partir de una imagen.',
    seoTitle: 'Generador de favicon (ICO y PNG) online',
    description: 'Genera favicon.ico (16, 32 y 48 px), apple-touch-icon y los iconos de Android/PWA desde cualquier imagen, con el código HTML listo.',
    keywords: ['favicon', 'crear favicon', 'favicon ico', 'apple touch icon', 'iconos pwa', 'crear iconos'],
    fields: [img({ multiple: false, label: 'Imagen (idealmente cuadrada, 512 px o más)', accept: 'image/png,image/jpeg,image/webp,image/svg+xml' }), { name: 'fondo', type: 'color', label: 'Fondo (para Apple)', value: '#ffffff', half: true }, { name: 'margen', type: 'range', label: 'Margen', value: 0, min: 0, max: 30, half: true, suffix: '%' }],
    howto: { title: 'Cómo crear un favicon', steps: ['Sube una imagen cuadrada (un logo o símbolo simple funciona mejor).', 'Pulsa Generar.', 'Descarga el ZIP y copia el código HTML en el <head> de tu web.'] },
    about: ['Un favicon se ve a 16 px: usa un símbolo simple con buen contraste, no el logotipo completo con texto. Apple no admite transparencia en su icono, por eso se aplica el color de fondo.'],
    faq: [faqPriv, ['¿Qué archivos necesito realmente?', 'favicon.ico en la raíz, apple-touch-icon.png (180 px) y, si tu web es instalable, los PNG de 192 y 512 px en el manifest.']],
    related: ['redimensionar-imagen', 'extraer-colores', 'generador-meta-tags'],
  },
];
