const pdf = (extra = {}) => ({ name: 'archivos', type: 'file', label: 'Archivo PDF', accept: 'application/pdf', multiple: false, maxMB: 150, maxFiles: 1, ...extra });
const common = { family: 'pdf', icon: 'file', submit: 'Procesar' };
const faqPriv = ['¿Se sube mi PDF a un servidor?', 'No. El documento se procesa dentro de tu navegador y nunca sale de tu dispositivo. Puedes comprobarlo desconectando internet después de cargar la página: la herramienta sigue funcionando.'];
const faqEnc = ['¿Funciona con PDF protegidos?', 'Los PDF cifrados (con contraseña o con restricciones de edición) no se pueden modificar sin la contraseña. Si subes uno, la herramienta te lo indicará sin procesarlo.'];
const pages = (extra = {}) => ({ name: 'paginas', type: 'text', label: 'Páginas', placeholder: 'Ej.: 1-3, 5, 8-', half: true, ...extra });

export default [
  {
    ...common, slug: 'unir-pdf', name: 'Unir PDF', icon: 'merge', popularity: 95, submit: 'Unir PDF',
    short: 'Combina varios PDF en un único documento en el orden que elijas.',
    seoTitle: 'Unir PDF online gratis (sin subir archivos)',
    description: 'Une varios archivos PDF en uno solo, en el orden que quieras. Gratis, sin marcas de agua y sin subir tus documentos a ningún servidor.',
    keywords: ['juntar pdf', 'combinar pdf', 'fusionar pdf', 'merge pdf', 'unir archivos pdf', 'pegar pdf'],
    fields: [pdf({ label: 'Archivos PDF', multiple: true, maxFiles: 50, sortable: true })],
    howto: { title: 'Cómo unir archivos PDF', steps: ['Arrastra los PDF o pulsa para elegirlos.', 'Ordénalos con las flechas.', 'Pulsa «Unir PDF» y descarga el documento combinado.'] },
    about: ['Se copian las páginas originales sin volver a comprimirlas, así que la calidad no cambia. Los enlaces internos y marcadores del índice pueden perderse al combinar.'],
    faq: [faqPriv, faqEnc, ['¿Hay un límite de archivos?', 'Hasta 50 archivos por operación. El tamaño total depende de la memoria de tu dispositivo.']],
    related: ['dividir-pdf', 'reordenar-paginas-pdf', 'comprimir-pdf', 'jpg-a-pdf'],
  },
  {
    ...common, slug: 'dividir-pdf', name: 'Dividir PDF', icon: 'split', popularity: 85, submit: 'Dividir PDF',
    short: 'Separa un PDF en varios archivos: por rangos, cada página suelta o extrayendo solo las que necesitas.',
    seoTitle: 'Dividir PDF online: separar páginas gratis',
    description: 'Divide un PDF en varios archivos por rangos de páginas, separa todas las páginas o extrae solo las que necesitas. Sin subir el documento.',
    keywords: ['separar pdf', 'extraer paginas pdf', 'cortar pdf', 'split pdf', 'separar hojas pdf', 'sacar una pagina de un pdf'],
    fields: [pdf(), { name: 'modo', type: 'select', label: 'Modo', value: 'rangos', half: true, options: [['rangos', 'Un PDF por cada rango'], ['extraer', 'Extraer páginas en un solo PDF'], ['todas', 'Cada página por separado']] }, pages({ showIf: 'modo!=todas', placeholder: 'Ej.: 1-3, 4-6, 7-' })],
    howto: { title: 'Cómo dividir un PDF', steps: ['Elige el PDF.', 'Indica los rangos (1-3, 4-6…) o elige «Cada página por separado».', 'Descarga los PDF resultantes, sueltos o en un ZIP.'] },
    faq: [faqPriv, faqEnc, ['¿Cómo escribo los rangos?', 'Separa con comas: «1-3, 5, 8-» crea tres documentos: páginas 1 a 3, la 5, y de la 8 al final.']],
    related: ['unir-pdf', 'eliminar-paginas-pdf', 'pdf-a-jpg'],
  },
  {
    ...common, slug: 'comprimir-pdf', name: 'Comprimir PDF', icon: 'compress', popularity: 95, submit: 'Comprimir PDF',
    short: 'Reduce el tamaño de un PDF: optimización sin pérdida o compresión fuerte para PDF escaneados.',
    seoTitle: 'Comprimir PDF online gratis (sin subir el archivo)',
    description: 'Reduce el peso de tus PDF en el navegador: optimización sin pérdida o compresión fuerte de PDF escaneados y con muchas imágenes.',
    keywords: ['reducir tamaño pdf', 'reducir peso pdf', 'comprimir pdf', 'hacer pdf mas pequeño', 'compress pdf', 'pdf pesa mucho'],
    fields: [pdf(), { name: 'nivel', type: 'select', label: 'Compresión', value: 'fuerte', options: [['sin', 'Sin pérdida (mantiene el texto seleccionable)'], ['fuerte', 'Fuerte, para escaneados (convierte páginas en imagen)'], ['extrema', 'Extrema (menor calidad)']] }],
    howto: { title: 'Cómo comprimir un PDF', steps: ['Sube el archivo.', 'Elige el nivel: sin pérdida para documentos de texto, fuerte para escaneados.', 'Descarga el resultado: verás cuánto se ha reducido.'] },
    about: ['«Sin pérdida» reorganiza la estructura interna del PDF y elimina datos redundantes: el documento queda idéntico. «Fuerte» vuelve a generar cada página como imagen JPG a 150 ppp: reduce mucho los escaneos y fotos, pero el texto deja de ser seleccionable. Si el resultado pesa más que el original, te lo indicamos y conservas el tuyo.'],
    faq: [faqPriv, ['¿Por qué mi PDF casi no se reduce?', 'Los PDF de texto generados por Word o similares ya son muy ligeros. La compresión fuerte está pensada para escaneos y documentos con fotos.'], faqEnc],
    related: ['unir-pdf', 'dividir-pdf', 'comprimir-imagen', 'pdf-a-jpg'],
  },
  {
    ...common, slug: 'rotar-pdf', name: 'Rotar PDF', icon: 'rotate', popularity: 55, submit: 'Rotar PDF',
    short: 'Gira todas o algunas páginas de un PDF y guárdalo con la orientación corregida.',
    seoTitle: 'Rotar PDF online: girar páginas',
    description: 'Gira las páginas de un PDF 90°, 180° o 270° de forma permanente: todas o solo las que elijas.',
    keywords: ['girar pdf', 'rotar paginas pdf', 'cambiar orientacion pdf', 'pdf al reves'],
    fields: [pdf(), { name: 'giro', type: 'select', label: 'Giro', value: '90', half: true, options: [['90', '90° derecha'], ['180', '180°'], ['270', '90° izquierda']] }, pages({ help: 'Vacío = todas las páginas.' })],
    howto: { title: 'Cómo rotar un PDF', steps: ['Elige el PDF.', 'Indica el giro y, si quieres, solo algunas páginas.', 'Descarga el PDF girado.'] },
    faq: [faqPriv, faqEnc],
    related: ['reordenar-paginas-pdf', 'eliminar-paginas-pdf', 'unir-pdf'],
  },
  {
    ...common, slug: 'eliminar-paginas-pdf', name: 'Eliminar páginas de un PDF', icon: 'trash', popularity: 60, submit: 'Eliminar páginas',
    short: 'Borra páginas concretas de un PDF y descarga el documento sin ellas.',
    seoTitle: 'Eliminar páginas de un PDF online',
    description: 'Elimina una o varias páginas de un PDF indicando sus números o rangos. Rápido, gratis y sin subir el documento.',
    keywords: ['borrar paginas pdf', 'quitar paginas pdf', 'suprimir hojas pdf', 'delete pages pdf'],
    fields: [pdf(), pages({ label: 'Páginas a eliminar', placeholder: 'Ej.: 2, 5-7' })],
    howto: { title: 'Cómo eliminar páginas de un PDF', steps: ['Elige el PDF.', 'Escribe las páginas que quieres quitar.', 'Descarga el PDF resultante.'] },
    faq: [faqPriv, faqEnc],
    related: ['dividir-pdf', 'reordenar-paginas-pdf', 'rotar-pdf'],
  },
  {
    ...common, slug: 'reordenar-paginas-pdf', name: 'Reordenar páginas de un PDF', icon: 'sort', popularity: 45, submit: 'Reordenar',
    short: 'Cambia el orden de las páginas de un PDF escribiendo el nuevo orden.',
    seoTitle: 'Reordenar páginas de un PDF online',
    description: 'Cambia el orden de las páginas de un PDF, invierte el documento o duplica páginas indicando el nuevo orden.',
    keywords: ['ordenar paginas pdf', 'cambiar orden pdf', 'mover paginas pdf', 'invertir pdf'],
    fields: [pdf(), { name: 'modo', type: 'select', label: 'Modo', value: 'manual', half: true, options: [['manual', 'Orden personalizado'], ['invertir', 'Invertir el orden']] }, pages({ label: 'Nuevo orden', placeholder: 'Ej.: 3, 1, 2, 4-', showIf: 'modo=manual', help: 'Las páginas que no incluyas se eliminan.' })],
    howto: { title: 'Cómo reordenar un PDF', steps: ['Elige el PDF (verás cuántas páginas tiene).', 'Escribe el orden nuevo, por ejemplo «3, 1, 2, 4-».', 'Descarga el PDF reordenado.'] },
    faq: [faqPriv, ['¿Puedo repetir una página?', 'Sí: si escribes «1, 1, 2» la primera página aparecerá dos veces.']],
    related: ['eliminar-paginas-pdf', 'rotar-pdf', 'unir-pdf'],
  },
  {
    ...common, slug: 'jpg-a-pdf', name: 'JPG a PDF', icon: 'image', popularity: 85, submit: 'Crear PDF',
    short: 'Convierte fotos e imágenes JPG en un PDF, una por página.',
    seoTitle: 'Convertir JPG a PDF online gratis',
    description: 'Convierte imágenes JPG (y PNG o WebP) en un único PDF: tamaño A4, carta o ajustado a la imagen, con márgenes opcionales. Sin subir las fotos.',
    keywords: ['jpg a pdf', 'foto a pdf', 'imagen a pdf', 'pasar foto a pdf', 'convertir imagen en pdf', 'fotos a pdf', 'webp a pdf'],
    fields: [{ ...pdf({ label: 'Imágenes', accept: 'image/jpeg,image/png,image/webp', multiple: true, maxFiles: 100, maxMB: 40, sortable: true }) }, { name: 'tamano', type: 'select', label: 'Tamaño de página', value: 'a4', half: true, options: [['a4', 'A4'], ['carta', 'Carta (EE. UU.)'], ['imagen', 'Igual que la imagen']] }, { name: 'margen', type: 'select', label: 'Margen', value: '0', half: true, options: [['0', 'Sin margen'], ['20', 'Pequeño'], ['40', 'Grande']] }],
    howto: { title: 'Cómo convertir JPG a PDF', steps: ['Elige las imágenes y ordénalas.', 'Elige tamaño de página y margen.', 'Pulsa «Crear PDF» y descárgalo.'] },
    about: ['Cada imagen ocupa una página y se orienta automáticamente en vertical u horizontal según su forma. Las JPG se incrustan sin recomprimir, así que no pierden calidad.'],
    faq: [faqPriv, ['¿Puedo mezclar JPG y PNG?', 'Sí. También admite WebP, que se convierte internamente.']],
    related: ['png-a-pdf', 'unir-pdf', 'comprimir-imagen', 'pdf-a-jpg'],
  },
  {
    ...common, slug: 'png-a-pdf', name: 'PNG a PDF', icon: 'image', popularity: 55, submit: 'Crear PDF',
    short: 'Convierte imágenes PNG, capturas y diagramas en un documento PDF.',
    seoTitle: 'Convertir PNG a PDF online gratis',
    description: 'Convierte capturas de pantalla e imágenes PNG en un PDF sin perder nitidez ni transparencia. Varias imágenes, una por página.',
    keywords: ['png a pdf', 'captura a pdf', 'pasar png a pdf', 'imagen png en pdf'],
    fields: [pdf({ label: 'Imágenes', accept: 'image/png,image/jpeg,image/webp', multiple: true, maxFiles: 100, maxMB: 40, sortable: true }), { name: 'tamano', type: 'select', label: 'Tamaño de página', value: 'imagen', half: true, options: [['a4', 'A4'], ['carta', 'Carta (EE. UU.)'], ['imagen', 'Igual que la imagen']] }, { name: 'margen', type: 'select', label: 'Margen', value: '0', half: true, options: [['0', 'Sin margen'], ['20', 'Pequeño'], ['40', 'Grande']] }],
    howto: { title: 'Cómo convertir PNG a PDF', steps: ['Elige las imágenes PNG.', 'Ordénalas y elige el tamaño de página.', 'Descarga el PDF.'] },
    about: ['PNG se incrusta sin pérdida, ideal para capturas con texto. Si el PDF resulta pesado, comprime antes las capturas o conviértelas a JPG.'],
    faq: [faqPriv],
    related: ['jpg-a-pdf', 'unir-pdf', 'png-a-jpg'],
  },
  {
    ...common, slug: 'pdf-a-jpg', name: 'PDF a JPG', icon: 'image', popularity: 80, submit: 'Convertir a JPG',
    short: 'Convierte cada página de un PDF en una imagen JPG o PNG de alta calidad.',
    seoTitle: 'Convertir PDF a JPG online gratis',
    description: 'Convierte las páginas de un PDF en imágenes JPG o PNG a 72, 150 o 300 ppp. Todas o solo algunas páginas, sin subir el documento.',
    keywords: ['pdf a imagen', 'pdf a jpg', 'pdf a png', 'convertir pdf en foto', 'pasar pdf a imagen', 'pdf to jpg'],
    fields: [pdf(), { name: 'formato', type: 'select', label: 'Formato', value: 'jpeg', half: true, options: [['jpeg', 'JPG'], ['png', 'PNG']] }, { name: 'ppp', type: 'select', label: 'Resolución', value: '150', half: true, options: [['72', '72 ppp (pantalla)'], ['150', '150 ppp (recomendado)'], ['300', '300 ppp (impresión)']] }, pages({ help: 'Vacío = todas.' })],
    howto: { title: 'Cómo convertir un PDF a JPG', steps: ['Elige el PDF.', 'Selecciona formato y resolución.', 'Descarga las imágenes sueltas o en un ZIP.'] },
    faq: [faqPriv, faqEnc, ['¿Qué resolución elijo?', '150 ppp para verlas en pantalla o compartir; 300 ppp si vas a imprimir. A 300 ppp una página A4 ocupa 2480×3508 px.']],
    related: ['jpg-a-pdf', 'pdf-a-texto', 'dividir-pdf', 'comprimir-imagen'],
  },
  {
    ...common, slug: 'pdf-a-texto', name: 'PDF a texto', icon: 'text', popularity: 55, submit: 'Extraer texto',
    short: 'Extrae el texto de un PDF para copiarlo o guardarlo como .txt.',
    seoTitle: 'Extraer texto de un PDF online',
    description: 'Extrae el texto de un PDF y cópialo o descárgalo como archivo .txt, página a página. Sin subir el documento.',
    keywords: ['pdf a txt', 'copiar texto pdf', 'extraer texto pdf', 'pdf to text', 'sacar texto de pdf'],
    fields: [pdf(), pages({ help: 'Vacío = todas.' })],
    howto: { title: 'Cómo extraer el texto de un PDF', steps: ['Elige el PDF.', 'Pulsa «Extraer texto».', 'Copia el texto o descárgalo como .txt.'] },
    about: ['Funciona con PDF que contienen texto real. Si el PDF es un escaneo (una foto de cada página), no hay texto que extraer: necesitarías OCR.'],
    faq: [faqPriv, ['El resultado sale vacío o con símbolos raros, ¿por qué?', 'El PDF es un escaneo o usa fuentes sin tabla de caracteres. En ese caso el texto solo existe como imagen.']],
    related: ['pdf-a-jpg', 'limpiar-texto', 'contador-palabras'],
  },
  {
    ...common, slug: 'contador-paginas-pdf', name: 'Contador de páginas PDF', icon: 'hash', popularity: 30, submit: 'Contar páginas', live: false,
    short: 'Cuenta las páginas de uno o muchos PDF a la vez y muestra el total.',
    seoTitle: 'Contar páginas de PDF online',
    description: 'Cuenta las páginas de varios PDF a la vez y obtén el total, útil para presupuestos de impresión o traducción.',
    keywords: ['contar paginas pdf', 'numero de paginas pdf', 'cuantas paginas tiene un pdf'],
    fields: [pdf({ label: 'Archivos PDF', multiple: true, maxFiles: 200 })],
    howto: { title: 'Cómo contar las páginas de varios PDF', steps: ['Elige uno o varios PDF.', 'Pulsa «Contar páginas».', 'Consulta el total y el detalle por archivo.'] },
    faq: [faqPriv],
    related: ['analizador-pdf', 'unir-pdf', 'dividir-pdf'],
  },
  {
    ...common, slug: 'analizador-pdf', name: 'Analizador de PDF', icon: 'search', popularity: 25, submit: 'Analizar',
    short: 'Muestra los metadatos, versión, tamaño de página, formularios y seguridad de un PDF.',
    seoTitle: 'Analizar PDF: metadatos y propiedades online',
    description: 'Consulta las propiedades de un PDF: título, autor, programa creador, fechas, versión, tamaño de página, formularios y cifrado.',
    keywords: ['metadatos pdf', 'propiedades pdf', 'info pdf', 'ver autor pdf', 'version pdf'],
    fields: [pdf()],
    howto: { title: 'Cómo ver las propiedades de un PDF', steps: ['Elige el PDF.', 'Pulsa «Analizar».', 'Revisa metadatos, páginas y seguridad.'] },
    about: ['Útil antes de enviar un documento: los metadatos pueden revelar el autor original, la empresa o el programa usado. Si no quieres compartirlos, vuelve a guardar el PDF desde un programa que permita editarlos.'],
    faq: [faqPriv],
    related: ['contador-paginas-pdf', 'comprimir-pdf', 'pdf-a-texto'],
  },
];
