const common = { family: 'seo', icon: 'search', live: true };

export default [
  {
    ...common, slug: 'vista-previa-serp', name: 'Vista previa en Google (SERP)', popularity: 55,
    short: 'Comprueba cómo se verán tu título y meta descripción en Google y si se cortarán.',
    seoTitle: 'Vista previa SERP: simulador de resultados de Google',
    description: 'Simula cómo aparecerá tu página en Google: título, URL y meta descripción con aviso de longitud en píxeles y caracteres.',
    keywords: ['serp preview', 'simulador google', 'meta title', 'longitud titulo seo', 'meta description', 'snippet google', 'generador de titulos'],
    fields: [{ name: 'titulo', type: 'text', label: 'Título (title)', placeholder: 'Comprimir PDF online gratis | Utilia', counter: 60 }, { name: 'url', type: 'text', label: 'URL', placeholder: 'https://ejemplo.com/herramientas/pdf/comprimir-pdf' }, { name: 'descripcion', type: 'textarea', label: 'Meta description', rows: 3, placeholder: 'Reduce el tamaño de tus PDF…', counter: 155 }],
    howto: { title: 'Cómo previsualizar tu resultado en Google', steps: ['Escribe el título y la meta description.', 'Añade la URL.', 'Ajusta hasta que nada quede cortado.'] },
    about: ['Google corta el título hacia los 580–600 px de ancho (unos 55–60 caracteres) y la descripción hacia los 920 px (unos 150–160 caracteres) en escritorio. Coloca lo importante al principio: en móvil el espacio es parecido pero se muestran más líneas.', 'Google puede reescribir tu título o descripción si considera que no describen bien la página. Un título único, concreto y alineado con el H1 reduce esa probabilidad.'],
    faq: [['¿Por qué se mide en píxeles?', 'Porque las letras no ocupan lo mismo: «WWW» es más ancho que «iii». El límite real de Google es visual, no de caracteres.']],
    related: ['generador-meta-tags', 'generador-slug', 'contador-caracteres'],
  },
  {
    ...common, slug: 'generador-meta-tags', name: 'Generador de meta tags', icon: 'code', popularity: 45, live: true,
    short: 'Genera las etiquetas meta, Open Graph y Twitter Card para el <head> de tu página.',
    seoTitle: 'Generador de meta tags, Open Graph y Twitter Card',
    description: 'Genera el código de las etiquetas title, meta description, canonical, Open Graph y Twitter Card listo para pegar en tu HTML.',
    keywords: ['meta tags', 'open graph', 'og tags', 'twitter card', 'meta title generator', 'meta description generator', 'etiquetas meta'],
    fields: [{ name: 'titulo', type: 'text', label: 'Título', counter: 60 }, { name: 'descripcion', type: 'textarea', label: 'Descripción', rows: 3, counter: 155 }, { name: 'url', type: 'text', label: 'URL canónica', placeholder: 'https://', half: true }, { name: 'imagen', type: 'text', label: 'Imagen para compartir (URL)', placeholder: 'https://…/og.jpg · 1200×630', half: true },
      { name: 'sitio', type: 'text', label: 'Nombre del sitio', half: true }, { name: 'tipo', type: 'select', label: 'Tipo', value: 'website', half: true, options: [['website', 'Web'], ['article', 'Artículo'], ['product', 'Producto']] }, { name: 'twitter', type: 'text', label: 'Usuario de X/Twitter', placeholder: '@usuario', half: true }, { name: 'idioma', type: 'text', label: 'Idioma (locale)', value: 'es_ES', half: true }],
    howto: { title: 'Cómo generar meta tags', steps: ['Rellena título, descripción y URL.', 'Añade la imagen para redes (1200×630 px).', 'Copia el código y pégalo dentro de <head>.'] },
    about: ['Open Graph controla cómo se ve tu enlace al compartirlo en WhatsApp, LinkedIn, Facebook o Slack. Sin og:image, cada red elegirá una imagen al azar o ninguna.'],
    faq: [['¿Qué tamaño debe tener la imagen?', '1200×630 px (proporción 1,91:1), menos de 5 MB, en JPG o PNG. Deja el contenido importante en el centro porque algunas apps recortan los bordes.']],
    related: ['vista-previa-serp', 'generador-robots-txt', 'generador-favicon'],
  },
  {
    ...common, slug: 'generador-robots-txt', name: 'Generador de robots.txt', icon: 'robot', popularity: 35,
    short: 'Crea un robots.txt correcto: rutas bloqueadas, sitemap y control de bots de IA.',
    seoTitle: 'Generador de robots.txt online',
    description: 'Genera un archivo robots.txt válido: permite o bloquea rutas, añade tu sitemap y decide si los rastreadores de IA pueden leer tu web.',
    keywords: ['robots txt', 'crear robots.txt', 'bloquear bots', 'gptbot', 'disallow', 'rastreadores ia'],
    fields: [{ name: 'modo', type: 'select', label: 'Acceso general', value: 'permitir', half: true, options: [['permitir', 'Permitir todo'], ['bloquear', 'Bloquear todo (web en desarrollo)']] }, { name: 'sitemap', type: 'text', label: 'URL del sitemap', placeholder: 'https://ejemplo.com/sitemap.xml', half: true },
      { name: 'bloquear', type: 'textarea', label: 'Rutas a bloquear (una por línea)', rows: 4, placeholder: '/admin/\n/carrito/\n/*?orden=', showIf: 'modo=permitir' }, { name: 'ia', type: 'checkbox', label: 'Bloquear rastreadores de entrenamiento de IA (GPTBot, CCBot, Google-Extended…)' }],
    howto: { title: 'Cómo crear un robots.txt', steps: ['Elige si permitir el acceso general.', 'Añade las rutas privadas y la URL del sitemap.', 'Descarga el archivo y súbelo a la raíz de tu dominio.'] },
    about: ['robots.txt es una petición, no una barrera: los bots maliciosos lo ignoran. Para ocultar algo de Google usa la etiqueta noindex o protégelo con contraseña; bloquear una URL en robots.txt no impide que se indexe si recibe enlaces.'],
    faq: [['¿Bloquear bots de IA afecta a mi posicionamiento en Google?', 'No. Google-Extended solo controla el uso para entrenar Gemini; Googlebot, que indexa para el buscador, no se ve afectado.']],
    related: ['generador-sitemap', 'generador-meta-tags', 'analizador-encabezados'],
  },
  {
    ...common, slug: 'generador-sitemap', name: 'Generador de sitemap XML', icon: 'sitemap', popularity: 30,
    short: 'Convierte una lista de URLs en un sitemap.xml válido.',
    seoTitle: 'Generador de sitemap XML online',
    description: 'Genera un sitemap.xml válido a partir de una lista de URLs, con fecha de modificación opcional. Detecta URLs duplicadas o no válidas.',
    keywords: ['sitemap', 'sitemap xml', 'crear sitemap', 'mapa del sitio', 'sitemap generator'],
    fields: [{ name: 'urls', type: 'textarea', label: 'URLs (una por línea)', rows: 8, placeholder: 'https://ejemplo.com/\nhttps://ejemplo.com/contacto', mono: true }, { name: 'fecha', type: 'date', label: 'Fecha de última modificación (opcional)', value: 'today', half: true }],
    howto: { title: 'Cómo crear un sitemap', steps: ['Pega las URLs de tu web.', 'Opcional: indica la fecha de última modificación.', 'Descarga sitemap.xml, súbelo a la raíz y envíalo en Google Search Console.'] },
    about: ['Google ignora las etiquetas priority y changefreq, por eso no se incluyen. Lo útil es lastmod, siempre que sea real: si todas las URLs tienen la fecha de hoy sin cambios, Google deja de fiarse de ella.'],
    faq: [['¿Cuántas URLs admite un sitemap?', 'Hasta 50.000 URLs o 50 MB sin comprimir. Si tienes más, divide en varios sitemaps y crea un índice.']],
    related: ['generador-robots-txt', 'generador-meta-tags'],
  },
  {
    ...common, slug: 'densidad-palabras-clave', name: 'Densidad de palabras clave', icon: 'chart', popularity: 35,
    short: 'Analiza qué palabras y frases se repiten más en un texto y su densidad.',
    seoTitle: 'Densidad de palabras clave (keyword density)',
    description: 'Calcula la densidad de palabras clave de un texto: palabras y frases de 2 o 3 palabras más repetidas, con su frecuencia y porcentaje.',
    keywords: ['keyword density', 'densidad de keywords', 'palabras repetidas', 'analizar texto seo', 'frecuencia de palabras'],
    fields: [{ name: 'texto', type: 'textarea', label: 'Texto', rows: 10 }, { name: 'n', type: 'select', label: 'Analizar', value: '1', half: true, options: [['1', 'Palabras sueltas'], ['2', 'Frases de 2 palabras'], ['3', 'Frases de 3 palabras']] }, { name: 'stop', type: 'checkbox', label: 'Ignorar palabras vacías (de, la, que…)', value: true, half: true }],
    howto: { title: 'Cómo analizar la densidad de palabras clave', steps: ['Pega el texto de tu página.', 'Elige palabras sueltas o frases.', 'Revisa si la palabra clave aparece de forma natural.'] },
    about: ['No existe una densidad «ideal». Google entiende sinónimos y contexto; repetir una palabra clave en exceso (keyword stuffing) empeora la lectura y puede perjudicar. Úsalo para detectar repeticiones forzadas o temas que faltan.'],
    faq: [['¿Qué densidad es buena?', 'La que resulta de escribir con naturalidad. Si una palabra supera el 3–4 % en un texto largo, probablemente suena repetitiva.']],
    related: ['contador-palabras', 'vista-previa-serp', 'analizador-encabezados'],
  },
  {
    ...common, slug: 'analizador-encabezados', name: 'Analizador de encabezados', icon: 'heading', popularity: 25, live: false, submit: 'Analizar',
    short: 'Revisa la estructura H1–H6 de una página HTML y detecta errores de jerarquía.',
    seoTitle: 'Analizador de encabezados H1-H6',
    description: 'Pega el HTML de una página y obtén su estructura de encabezados H1–H6, con avisos de H1 múltiples, saltos de nivel y encabezados vacíos.',
    keywords: ['heading analyzer', 'estructura h1', 'encabezados html', 'jerarquia h1 h2', 'seo on page'],
    fields: [{ name: 'html', type: 'textarea', label: 'Código HTML', rows: 10, mono: true, placeholder: '<h1>Título</h1>\n<h2>Sección</h2>', help: 'En tu navegador: clic derecho → «Ver código fuente» → copiar todo.' }],
    howto: { title: 'Cómo revisar los encabezados de una página', steps: ['Copia el código fuente de la página.', 'Pégalo y pulsa Analizar.', 'Corrige los avisos de jerarquía.'] },
    about: ['Una buena estructura tiene un único H1 que describe la página y encabezados que bajan de nivel sin saltos (H2 → H3, no H2 → H4). Ayuda a los lectores de pantalla tanto como a los buscadores.'],
    faq: [['¿Se descarga la página por mí?', 'No: por privacidad y seguridad el análisis se hace sobre el HTML que pegas, sin conectarse a ninguna web.']],
    related: ['densidad-palabras-clave', 'vista-previa-serp', 'generador-meta-tags'],
  },
];
