const texto = (extra = {}) => ({ name: 'texto', type: 'textarea', label: 'Texto', placeholder: 'Escribe o pega aquí tu texto…', rows: 10, ...extra });
const statsFaq = [
  ['¿Cómo se cuentan las palabras?', 'Se considera palabra cualquier secuencia de letras o números separada por espacios o signos de puntuación. «Coche-cama» cuenta como dos palabras y los números como «2026» cuentan como una.'],
  ['¿Cómo se calcula el tiempo de lectura?', 'Se usa una velocidad media de 230 palabras por minuto para lectura silenciosa y 150 para leer en voz alta.'],
];

export default [
  {
    slug: 'contador-palabras', name: 'Contador de palabras', family: 'text', icon: 'text', live: true, popularity: 95,
    short: 'Cuenta palabras, caracteres, frases y párrafos al instante mientras escribes.',
    seoTitle: 'Contador de palabras online gratis',
    description: 'Cuenta palabras, caracteres con y sin espacios, frases, párrafos y tiempo de lectura de cualquier texto. Gratis, instantáneo y sin enviar tu texto.',
    keywords: ['contar palabras', 'numero de palabras', 'cuantas palabras tiene', 'word counter', 'contador de texto'],
    fields: [texto()], options: { focus: 'palabras' },
    howto: { title: 'Cómo contar las palabras de un texto', steps: ['Escribe o pega el texto en el recuadro.', 'El recuento se actualiza al instante mientras escribes.', 'Consulta palabras, caracteres, frases, párrafos y tiempo de lectura.'] },
    about: ['Útil para trabajos con límite de palabras, artículos, descripciones de producto o traducciones que se presupuestan por palabra. Las palabras más repetidas te ayudan a detectar muletillas.'],
    faq: statsFaq,
    related: ['contador-caracteres', 'contador-lineas', 'densidad-palabras-clave', 'limpiar-texto'],
  },
  {
    slug: 'contador-caracteres', name: 'Contador de caracteres', family: 'text', icon: 'text', live: true, popularity: 85,
    short: 'Cuenta caracteres con y sin espacios, ideal para redes sociales, SMS y meta descripciones.',
    seoTitle: 'Contador de caracteres online (con y sin espacios)',
    description: 'Cuenta los caracteres de un texto con y sin espacios al instante. Comprueba límites de X/Twitter, SMS, meta descripciones y formularios.',
    keywords: ['contar caracteres', 'contar letras', 'caracteres con espacios', 'caracteres sin espacios', 'limite caracteres'],
    fields: [texto()], options: { focus: 'caracteres' },
    howto: { title: 'Cómo contar caracteres', steps: ['Pega o escribe tu texto.', 'Mira el total con y sin espacios.', 'Compara con los límites habituales que se muestran debajo.'] },
    about: ['Los emojis y letras con tilde cuentan como un carácter, igual que hacen la mayoría de redes sociales. Límites de referencia: X/Twitter 280, SMS 160 (70 si hay emojis o caracteres especiales), meta description ~155.'],
    faq: [['¿Un emoji cuenta como un carácter?', 'Aquí sí: se cuentan grafemas, es decir, lo que ves como un único símbolo. Algunos sistemas antiguos cuentan ciertos emojis como 2 o más.'], ...statsFaq.slice(1)],
    related: ['contador-palabras', 'vista-previa-serp', 'contador-lineas'],
  },
  {
    slug: 'contador-lineas', name: 'Contador de líneas', family: 'text', icon: 'text', live: true, popularity: 40,
    short: 'Cuenta líneas totales, líneas con contenido y líneas vacías de un texto.',
    seoTitle: 'Contador de líneas online',
    description: 'Cuenta cuántas líneas tiene un texto, cuántas tienen contenido y cuántas están vacías. Útil para listas, código y CSV.',
    keywords: ['contar lineas', 'numero de lineas', 'lineas vacias'],
    fields: [texto()], options: { focus: 'lineas' },
    howto: { title: 'Cómo contar líneas', steps: ['Pega el texto, lista o código.', 'Consulta las líneas totales, con contenido y vacías.'] },
    faq: [['¿Cuenta la última línea si está vacía?', 'Un salto de línea final no crea una línea extra: se ignora, igual que hacen los editores de código.']],
    related: ['ordenar-lineas', 'eliminar-lineas-duplicadas', 'contador-palabras'],
  },
  {
    slug: 'mayusculas-minusculas', name: 'Convertir mayúsculas y minúsculas', family: 'text', icon: 'case', live: true, popularity: 70,
    short: 'Pasa un texto a MAYÚSCULAS, minúsculas, Tipo Título, tipo frase, camelCase, snake_case y más.',
    seoTitle: 'Convertir texto a mayúsculas o minúsculas online',
    description: 'Convierte texto a mayúsculas, minúsculas, tipo título, tipo oración, camelCase, snake_case o kebab-case con un clic.',
    keywords: ['pasar a mayusculas', 'pasar a minusculas', 'convertir mayusculas', 'tipo titulo', 'camelcase', 'snake case', 'quitar mayusculas'],
    fields: [texto(), { name: 'modo', type: 'select', label: 'Convertir a', value: 'upper', options: [['upper', 'MAYÚSCULAS'], ['lower', 'minúsculas'], ['title', 'Tipo Título'], ['sentence', 'Tipo oración'], ['invert', 'iNVERTIR mAYÚSCULAS'], ['camel', 'camelCase'], ['pascal', 'PascalCase'], ['snake', 'snake_case'], ['kebab', 'kebab-case'], ['constant', 'CONSTANT_CASE']] }],
    howto: { title: 'Cómo cambiar mayúsculas y minúsculas', steps: ['Pega el texto.', 'Elige el formato de destino.', 'Copia o descarga el resultado.'] },
    faq: [['¿Respeta las tildes y la ñ?', 'Sí. La conversión usa las reglas del español, así que «ñandú» pasa a «ÑANDÚ» correctamente.']],
    related: ['limpiar-texto', 'generador-slug', 'buscar-reemplazar'],
  },
  {
    slug: 'limpiar-texto', name: 'Limpiar texto', family: 'text', icon: 'eraser', live: true, popularity: 60,
    short: 'Elimina espacios duplicados, líneas vacías, etiquetas HTML y caracteres invisibles de un texto.',
    seoTitle: 'Limpiar texto online: quitar espacios dobles y líneas vacías',
    description: 'Limpia texto copiado de PDF, webs o Word: quita espacios duplicados, líneas vacías, saltos de línea, etiquetas HTML y caracteres invisibles.',
    keywords: ['eliminar espacios duplicados', 'quitar espacios', 'quitar saltos de linea', 'eliminar lineas vacias', 'quitar html', 'quitar tildes', 'limpiar formato'],
    fields: [texto(),
      { name: 'espacios', type: 'checkbox', label: 'Espacios duplicados', value: true, half: true },
      { name: 'recortar', type: 'checkbox', label: 'Espacios al inicio/fin de línea', value: true, half: true },
      { name: 'vacias', type: 'checkbox', label: 'Líneas vacías', value: true, half: true },
      { name: 'saltos', type: 'checkbox', label: 'Unir líneas (quitar saltos)', half: true },
      { name: 'html', type: 'checkbox', label: 'Etiquetas HTML', half: true },
      { name: 'invisibles', type: 'checkbox', label: 'Caracteres invisibles', value: true, half: true },
      { name: 'tildes', type: 'checkbox', label: 'Quitar tildes', half: true },
      { name: 'comillas', type: 'checkbox', label: 'Comillas tipográficas → rectas', half: true }],
    howto: { title: 'Cómo limpiar un texto', steps: ['Pega el texto con el formato roto.', 'Marca las limpiezas que quieras aplicar.', 'Copia el texto limpio.'] },
    about: ['El caso típico: copiar de un PDF deja saltos de línea en mitad de las frases. Activa «Unir líneas» para recuperar párrafos continuos; los párrafos separados por una línea en blanco se conservan.'],
    faq: [['¿Qué son los caracteres invisibles?', 'Espacios de ancho cero, marcas de dirección o espacios de no separación que se cuelan al copiar de webs y rompen búsquedas o validaciones.']],
    related: ['mayusculas-minusculas', 'buscar-reemplazar', 'eliminar-lineas-duplicadas'],
  },
  {
    slug: 'ordenar-lineas', name: 'Ordenar líneas', family: 'text', icon: 'sort', live: true, popularity: 35,
    short: 'Ordena alfabéticamente, por longitud, al revés o al azar las líneas de una lista.',
    seoTitle: 'Ordenar líneas alfabéticamente online',
    description: 'Ordena listas alfabéticamente (A-Z o Z-A), numéricamente, por longitud, al revés o aleatoriamente.',
    keywords: ['ordenar alfabeticamente', 'ordenar lista', 'orden aleatorio', 'invertir lista', 'sort lines'],
    fields: [texto({ placeholder: 'Una entrada por línea…' }),
      { name: 'orden', type: 'select', label: 'Orden', value: 'az', half: true, options: [['az', 'A → Z'], ['za', 'Z → A'], ['len', 'Más cortas primero'], ['lendesc', 'Más largas primero'], ['reverse', 'Invertir orden actual'], ['random', 'Aleatorio']] },
      { name: 'vacias', type: 'checkbox', label: 'Quitar líneas vacías', value: true, half: true }],
    howto: { title: 'Cómo ordenar una lista', steps: ['Pega la lista, una entrada por línea.', 'Elige el tipo de orden.', 'Copia la lista ordenada.'] },
    faq: [['¿Ordena bien los números?', 'Sí: se usa orden natural, así que «2» va antes que «10», y las tildes se ordenan como en español.']],
    related: ['eliminar-lineas-duplicadas', 'contador-lineas', 'limpiar-texto'],
  },
  {
    slug: 'eliminar-lineas-duplicadas', name: 'Eliminar líneas duplicadas', family: 'text', icon: 'copy', live: true, popularity: 40,
    short: 'Quita las líneas repetidas de una lista conservando el orden original.',
    seoTitle: 'Eliminar duplicados de una lista online',
    description: 'Elimina líneas duplicadas de listas de emails, palabras clave o datos, manteniendo la primera aparición y el orden.',
    keywords: ['quitar duplicados', 'eliminar repetidos', 'lineas repetidas', 'remove duplicates', 'lista unica'],
    fields: [texto({ placeholder: 'Una entrada por línea…' }),
      { name: 'mayus', type: 'checkbox', label: 'Ignorar mayúsculas', value: true, half: true },
      { name: 'recortar', type: 'checkbox', label: 'Ignorar espacios al inicio/fin', value: true, half: true }],
    howto: { title: 'Cómo eliminar duplicados', steps: ['Pega la lista.', 'Elige si «Hola» y «hola» cuentan como iguales.', 'Copia la lista sin repetidos.'] },
    faq: [['¿Qué versión se conserva?', 'La primera aparición de cada línea, en su posición original.']],
    related: ['ordenar-lineas', 'contador-lineas', 'limpiar-texto'],
  },
  {
    slug: 'buscar-reemplazar', name: 'Buscar y reemplazar', family: 'text', icon: 'replace', live: true, popularity: 35,
    short: 'Reemplaza palabras o patrones en un texto, con opción de expresiones regulares.',
    seoTitle: 'Buscar y reemplazar texto online',
    description: 'Busca y reemplaza palabras en un texto largo, distinguiendo mayúsculas o usando expresiones regulares.',
    keywords: ['reemplazar palabras', 'sustituir texto', 'find replace', 'cambiar palabra'],
    fields: [texto(),
      { name: 'buscar', type: 'text', label: 'Buscar', half: true },
      { name: 'reemplazar', type: 'text', label: 'Reemplazar por', half: true },
      { name: 'mayus', type: 'checkbox', label: 'Distinguir mayúsculas', half: true },
      { name: 'regex', type: 'checkbox', label: 'Expresión regular', half: true }],
    howto: { title: 'Cómo reemplazar texto', steps: ['Pega el texto.', 'Escribe lo que buscas y el texto nuevo.', 'Copia el resultado; verás cuántos cambios se hicieron.'] },
    faq: [['¿Puedo usar grupos en el reemplazo?', 'Sí, con «Expresión regular» activado puedes usar $1, $2… para insertar grupos capturados.']],
    related: ['probador-regex', 'limpiar-texto', 'comparar-textos'],
  },
  {
    slug: 'lorem-ipsum', name: 'Generador de Lorem Ipsum', family: 'text', icon: 'paragraph', live: true, popularity: 45,
    short: 'Genera texto de relleno Lorem Ipsum por párrafos, frases o palabras.',
    seoTitle: 'Generador de Lorem Ipsum',
    description: 'Genera texto de relleno Lorem Ipsum para maquetas y diseños: elige párrafos, frases o palabras y cópialo.',
    keywords: ['texto de relleno', 'lorem ipsum', 'placeholder text', 'texto de prueba', 'generador de texto'],
    fields: [{ name: 'cantidad', type: 'number', label: 'Cantidad', value: 3, min: 1, max: 100, half: true },
      { name: 'unidad', type: 'select', label: 'Unidad', value: 'p', half: true, options: [['p', 'Párrafos'], ['f', 'Frases'], ['w', 'Palabras']] },
      { name: 'inicio', type: 'checkbox', label: 'Empezar con «Lorem ipsum dolor sit amet»', value: true },
      { name: 'html', type: 'checkbox', label: 'Envolver párrafos en <p>' }],
    howto: { title: 'Cómo generar Lorem Ipsum', steps: ['Indica cuánto texto necesitas.', 'Elige párrafos, frases o palabras.', 'Copia el texto generado.'] },
    faq: [['¿Qué significa Lorem Ipsum?', 'Es un fragmento alterado de «De finibus bonorum et malorum» de Cicerón (45 a. C.). Se usa porque su distribución de letras se parece a la de un texto real sin distraer con su significado.']],
    related: ['contador-palabras', 'generador-meta-tags'],
  },
  {
    slug: 'comparar-textos', name: 'Comparar textos', family: 'text', icon: 'diff', popularity: 50, submit: 'Comparar',
    short: 'Encuentra las diferencias entre dos textos línea a línea.',
    seoTitle: 'Comparar dos textos y ver diferencias online',
    description: 'Compara dos versiones de un texto o código y resalta las líneas añadidas, eliminadas y sin cambios.',
    keywords: ['diferencias entre textos', 'diff', 'comparador de textos', 'comparar documentos', 'text compare'],
    fields: [texto({ name: 'a', label: 'Texto original', placeholder: 'Versión original…', half: true }), texto({ name: 'b', label: 'Texto modificado', placeholder: 'Versión nueva…', half: true }),
      { name: 'espacios', type: 'checkbox', label: 'Ignorar espacios al inicio/fin' }],
    howto: { title: 'Cómo comparar dos textos', steps: ['Pega la versión original a la izquierda.', 'Pega la versión nueva a la derecha.', 'Pulsa Comparar: en verde lo añadido, en rojo lo eliminado.'] },
    faq: [['¿Hasta qué tamaño funciona?', 'Hasta unas 5.000 líneas por lado, suficiente para contratos, artículos o archivos de código.']],
    related: ['buscar-reemplazar', 'contador-palabras', 'formateador-json'],
  },
  {
    slug: 'generador-slug', name: 'Generador de slugs', family: 'text', icon: 'link', also: ['seo'], live: true, popularity: 40,
    short: 'Convierte un título en una URL limpia: minúsculas, sin tildes y con guiones.',
    seoTitle: 'Generador de slug para URLs amigables',
    description: 'Convierte títulos en slugs para URLs amigables: minúsculas, sin tildes ni caracteres especiales, separados por guiones.',
    keywords: ['url amigable', 'slug', 'permalink', 'friendly url', 'quitar tildes url'],
    fields: [texto({ label: 'Títulos (uno por línea)', placeholder: '¿Cómo comprimir un PDF sin perder calidad?', rows: 5 }),
      { name: 'separador', type: 'select', label: 'Separador', value: '-', half: true, options: [['-', 'Guion (-)'], ['_', 'Guion bajo (_)']] },
      { name: 'stop', type: 'checkbox', label: 'Quitar palabras vacías (de, la, el…)', half: true }],
    howto: { title: 'Cómo crear un slug', steps: ['Escribe el título (o varios, uno por línea).', 'Copia el slug generado.'] },
    faq: [['¿Debo quitar las palabras vacías?', 'No es obligatorio. Quitarlas acorta la URL, pero a veces cambia el sentido («sin» o «no» son importantes). Revísalo antes de publicar.']],
    related: ['vista-previa-serp', 'generador-meta-tags', 'mayusculas-minusculas'],
  },
];
